### ISSUE TITLE
Radio control instead of checkboxs for layer control

### ISSUE THREAD

**Issue by joaopalotti** [python-visualization/folium#1025]
Hi all,

First of all, thanks for this wonderful library.

I am planning to visualize different data slices on top of the same map.
For example, let's say that for the US Unemployment example (https://python-visualization.github.io/folium/docs-v0.6.0/quickstart.html#Choropleth-maps) I have information of unemployment by gender and education. 

How can I create an exclusive group control like was done by this plugin (https://github.com/ismyrnow/leaflet-groupedlayercontrol) here using a radio control instead of a checkbox?

**Comment by ocefpaf** [comment]
Every layer that has the option `overlay=True/False` can be set to a radio button and cycle the layers available. However, what you want is to group those layers with that plugin and this is not possible without the plugin ;-p

That functionality is a nice candidate for an external plugin but I don't believe it belongs in the core folium. (Happy to be convinced otherwise with a nice PR!)

**Comment by Conengmo** [comment]
This was added in https://github.com/python-visualization/folium/pull/1592, which will be available in the 0.14.0 release.
