### ISSUE TITLE
control markers using GeoJson

### ISSUE THREAD

**Issue by Alcampopiano** [python-visualization/folium#1059]
Hi all,

I can plot markers using `GeoJson` or `Marker`. I like using GeoJson since I can plot them all at once without a loop, and also I love `GeoJson.Tooltip`, which looks great. Please see below for an example.

Unfortunately, I can't figure out how to change the icon, or other properties of the markers when using `GeoJson`. If I switch to looping and using `Marker`, I have more control over the markers but the tooltips don't look as good when specifying a list of values (I get a string representation).

Is there a way to change properties of the markers using the `GeoJson` method?

```python
data={'type': 'FeatureCollection',
 'features': [{'id': '0',
  'type': 'Feature',
  'properties': {'SCHOOL_NAME': 'Ascension Elementary School',
   'SCHOOL_CODE': 'ACSN',
   'ADDRESS': '5205 New Street',
   'CITY': 'Burlington',
   'PROV': 'ON',
   'POST': 'L7L 1V3',
   'COUNTRY': 'Canada',
   'style': {'markerColor': '#00000000', 'color': '#00000000'},
   'highlight': {}},
  'geometry': {'type': 'Point', 'coordinates': [-79.7491672, 43.371468]}},
 {'id': '2',
  'type': 'Feature',
  'properties': {'SCHOOL_NAME': 'Bishop P. F. Reding Secondary School',
   'SCHOOL_CODE': 'BHRD',
   'ADDRESS': '1120 Main Street East',
   'CITY': 'Milton',
   'PROV': 'ON',
   'POST': 'L9T 6H7',
   'COUNTRY': 'Canada',
   'style': {'markerColor': '#00000000', 'color': '#00000000'},
   'highlight': {}},
  'geometry': {'type': 'Point',
   'coordinates': [-79.86306090000001, 43.530966799999995]}}]}

m = folium.Map(location=[43.342094, -79.803047], zoom_start=12)
folium.GeoJson(data, name='Schools', tooltip=folium.features.GeoJsonTooltip(fields=['SCHOOL_NAME', 'ADDRESS'], localize=True)).add_to(m)
m
```
![sc](https://user-images.githubusercontent.com/4624246/52085318-352aaf00-2572-11e9-8d9a-3ca41d6ae7d0.png)

Thanks so much for this incredible package.

Al

**Comment by ms77grz** [comment]
I've got the same problem with changing marker from GeoJson. Can't find any working example.

**Comment by Damorck** [comment]
Any progress on this issue?

**Comment by CriticalWill** [comment]
> 
> 
> Hey @Alcampopiano, glad you're enjoying the package.
> 
> I've got a PR in for this issue that I have been needing to finish up in #957. Just been quite busy working on a lot of really fun stuff at a new job. I'll try to get it wrapped up soon.

@jtbaker any word?

**Comment by Damorck** [comment]
@and-viceversa Thx for sharing that.

**Comment by mong220394** [comment]
Hi, I need help here. I tried all solutions above according to my dataset. Unfortunately, I failed to replicate them using MarkerCLuster in order to show the tooltip.

This is my code :

```
alerts_gj = alerts2geojson(alerts_df) #convert the dataframe to geojson

map = folium.Map(location = [alerts_df['latitude'].mean(), alerts_df['longitude'].mean()] ,zoom_start=10)
jam_cluster = plugins.MarkerCluster(control=False)
mc1= plugins.FeatureGroupSubGroup(jam_cluster, name='Jam2')

for f in alerts_gj['features']:
    popup = """
    Location : <b>%s</b><br>
    """ % (f['properties']['city'])

    if f['properties']['type'] == 'JAM' or f['properties']['type'] == 'JAM2':

        folium.Marker(location=f['geometry']['coordinates'],
                            tooltip=popup,
                            icon=folium.Icon(
                              icon_color='#ff033e',
                              icon='certificate',
                              prefix='fa')
                          ).add_to(jam_cluster)


map.add_child(jam_cluster)
map.add_child(mc1)
mc1.add_child(folium.GeoJson(alerts_gj, embed=False))
folium.LayerControl(collapsed=False).add_to(map)
map
```
`alerts_df` is a dataframe.
`alerts_gj` is a geojson.

Also, for some reason, I needed to tick and untick `Jam2` in order to display the cluster.

Thank you.

**Comment by and-viceversa** [comment]
@mong220394 I haven't used the MarkerCluster class, so I won't comment on that. But it looks like you need to change `for f in alerts_gj['features']:` to `for f in alerts_gj.data['features']:`.

You don't provide code for the `alerts2geojson` function. But `alerts_gj` must be a `folium.GeoJson` object.

Also, you may have better luck using `folium.Tooltip()` class instead of just passing a string.

Also it looks like Markers get added to `FeatureGroupSubGroup` and not the MarkerCluster. See [docs](https://python-visualization.github.io/folium/plugins.html#folium.plugins.FeatureGroupSubGroup)

**Comment by mong220394** [comment]
@and-viceversa Added `for f in alerts_gj.data['features']:` and receiving 
**AttributeError: data**. I edited `alerts2geojson` on the question. How do I know if its folium.GeoJson object?

**Comment by and-viceversa** [comment]
@mong220394 It looks like your `alerts2geojson` function is the issue here. You need to read in your source data using the `folium.GeoJson` class and then my above code samples can be modified for your use case.

As an alternative, you could use the coordinates/attributes in your existing dataframe to create the folium Markers. Creating geojson in the strict sense might be an extra step here if you're just plotting points.

See the GeoPandas examples [here](https://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/Geopandas_and_geo_interface.ipynb) for plotting data from a geopandas dataframe. The example pages in general will get you a long way.

Also check out the folium [Gitter](https://gitter.im/python-visualization/folium) - help questions might reach a wider audience.

**Comment by michelegentili93** [comment]
> Hey @Alcampopiano, glad you're enjoying the package.
> 
> I've got a PR in for this issue that I have been needing to finish up in #957. Just been quite busy working on a lot of really fun stuff at a new job. I'll try to get it wrapped up soon.

Hi Thanks for the branch, it hasn't be merged yet. I've download your branch, but I cannot find a way to modify marker color from geoJson. Could you provide an example with your branch?
Thank you!

**Comment by michelegentili93** [comment]
> Hey @Alcampopiano, glad you're enjoying the package.
> 
> I've got a PR in for this issue that I have been needing to finish up in #957. Just been quite busy working on a lot of really fun stuff at a new job. I'll try to get it wrapped up soon.

Thanks for the branch, but it hasn't merged yet? I try to download it and try it, but I'm not able to change the icon color from geoJson... could you provide an example? 

Thanks :)
