### ISSUE TITLE
Interactive timeline feature

### ISSUE THREAD

**Issue by nonoumasy** [python-visualization/folium#1061]
Wondering if folium has an interactive timeline feature yet?
Seems someone has made it for Leaflet.
http://skeate.github.io/Leaflet.timeline/earthquakes.html
In general, how easy would it be to add a feature to Folium once its implemented in Leaflet?

Note:
I just found a TimeSliderChoropleth available for Folium but I'm looking for a general feature that can also handle points and not just choropleths.

**Comment by Conengmo** [comment]
Hi @nonoumasy, can you share why you closed the issue?

Folium has a timestamped geojson plugin, does that work for you? https://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/Plugins.ipynb#Timestamped-GeoJSON

The plugin you link to seems interesting because it seems to work with any Leaflet object. If you want, you're welcome to look into this. It could likely be added to folium as a plugin. Though it would be good to first take stock of all time-related plugins we currently have.

**Comment by nonoumasy** [comment]
Hi Frank,

Thanks. I actually did see there was something close to what I was looking
for so I canceled the issue.
To be precise, what I am looking for is:

   1. a timeseries slider that works with points (not just choropleths)
   2. a slider I can style (with css) to fit my needs

thanks
N

[image: history project copy 3.png]

**Comment by Conengmo** [comment]
Maybe the `TimestampedGeoJson` plugin can be used for what you need. You first have to convert your points into a geojson geometry. You can do this with the `MultiPoint` geometry type: http://geojson.org/geojson-spec.html#multipoint

The slider on the page can be styled. You can use your browser developer tools to inspect it and see what classes you need to use to style it. You would have to add the css declarations with a bit of a hack though. You can do it by adding an element with a custom template to your map:

```
el = folium.MacroElement().add_to(m)
el._template = jinja2.Template("""
    {% macro header(this, kwargs) %}
    <style>
        .leaflet-control-timecontrol {background-color: red !important}
    </style>
    {% endmacro %}
""")
```

Hope that helps! If you (or somebody else) still wants to add a plugin with the Leaflet.timeline plugin that's welcome as well.

**Comment by nonoumasy** [comment]
thanks. will do
