### ISSUE TITLE
GeoJsonTooltip on Choropleth showing a pandas column?

### ISSUE THREAD

**Issue by joelluijmes** [python-visualization/folium#1074]
I want to have a tooltip on my Choropleth to show the actual value of a region. Specifically Im making a choropleth of Amsterdam with the count of customers in a certain postal code. 

```python
density = (df
    .reset_index()
    .rename(columns={'Id': 'Count'})
    .groupby('Postcode cijfers')
    .count()
)[['Count']].reset_index()

# Postcode cijfers, Count
# array([['1011', 213],
#        ['1012', 146],
#        ['1013', 402],
#        ['1014', 49],
#        ['1015', 354]], dtype=object)

m = folium.Map(location=(52.3740300, 4.8896900),
               min_zoom=11)

choropleth = folium.Choropleth('../Resources/PC4_BUURTEN.json',
                  name='Postal Codes',
                  data=density,
                  key_on='properties.Postcode4',
                  columns=['Postcode cijfers', 'Count'],
                  fill_color='YlGn',
                  fill_opacity=0.7,
                  line_opacity=0.2,
                  legend_name='Customer Count',
).add_to(m)

choropleth.geojson.add_child(
    folium.features.GeoJsonTooltip(['Postcode4'])
)
```

<img width="640" alt="image" src="https://user-images.githubusercontent.com/4273556/53247456-bb3e9f00-36b3-11e9-99f2-0043b61fead7.png">

#### Problem description

The [documentation](https://python-visualization.github.io/folium/docs-master/modules.html?highlight=chor#folium.features.GeoJsonTooltip) states:

> fields (list or tuple.) – Labels of GeoJson/TopoJson ‘properties’ or GeoPandas GeoDataFrame columns you’d like to display.

However when I try to add `Count` to the fields (`GeoJsonTooltip(['Postcode4', 'Count'])`) I get the following error:

> ```AssertionError: The field Count is not available in the data. Choose from: ('Postcode4', 'Opp_m2').```

Suggesting that it only looks to the GeoJSON properties list.

#### Question

How can I refer to the attached dataframe for showing the `Count` in the tooltip? Is there a possibility for this, or is the documentation wrong / did I misunderstood it?

In the mean time I could iterate over the GeoJSON and manually add the `Count` field to the properties.

**Comment by jtbaker** [comment]
Hi @joelluijmes - see #1060 (closed, but I think it should be reworth opening if we're interested in supporting the `Choropleth` class for the future.) for this issue. This has some underlying issues because of the way that the `Choropleth` class manages the underlying data structure. An optional workaround (for the short term) would be to merge your data together into a unified `GeoDataFrame` using `geopandas` and to work using the `folium.features.GeoJson` class.

**Comment by joelluijmes** [comment]
Alright, it would be nice thing to have. Thanks for your reply 👍 However maybe it is an idea to update the documentation that it currently isn't possible to show pandas data in the tooltip (or when using Choropleth.)

My current solution is altering the geojson and add the `Count` to the `properties`. Which works fine :)

**Comment by jtbaker** [comment]
The `Choropleth` class [documentation](https://python-visualization.github.io/folium/modules.html#module-folium.features) does not list tooltip functionality as a first-level class argument because of this  lack of complete functionality. Some users have just found it possible to add one via the `.add_child` method because `Choropleth` uses the `GeoJson` class under the hood. Since it's not advertised as a feature in the documentation, I don't think it's necessary to enumerate that limitation there. If advanced users would like to have more granular control over the class, I think the idea is to steer them towards direct `folium.features.GeoJson` class, where `Choropleth` is more of an intro to getting people started with the library.

 I've submitted a PR [here](https://github.com/jtbaker/folium/commit/3c0fba55edc683ecd54532b28d789df16b650a10) to add complete functionality to `Choropleth` that awaits further discussion.

**Comment by joelluijmes** [comment]
Ahh I see, so what you were suggesting is use the `GeoJson` class to create the choropleth, instead of using the `Choropleth` class? Is there an example notebook on that?

**Comment by jtbaker** [comment]
> you were suggesting is use the `GeoJson` class to create the choropleth

Yep! That will give you more granular control over the styling, highlighting etc. using the `style_function`, `highlight_function`, etc. kwargs.

>Is there an example notebook on that?

Check the [examples](https://nbviewer.jupyter.org/github/python-visualization/folium/tree/master/examples/) repository on NBViewer for some examples on how to those and other features of the library.

**Comment by pbower** [comment]
Is this something that can be re-considered? As a user it's really annoying to have to bounce this data back to the GeoJSON data structure instead of the convenience of using a pandas column.

**Comment by Conengmo** [comment]
folium is maintained by volunteers. We don't have a roadmap for new features, so it's all up to the users contributing. If you have a good idea on how to implement this in a simple and sane way, I'd be happy to discuss/review it.
