### ISSUE TITLE
Support for custom map panes

### ISSUE THREAD

**Issue by lpkirwin** [python-visualization/folium#1088]
Hi,

Is there currently any way in folium to work with panes as described here?

[https://leafletjs.com/examples/map-panes/](https://leafletjs.com/examples/map-panes/)

I've searched around, but didn't find anything. Same as in the link, my use-case is adding a label-only tile layer above a choropleth, i.e. this

![folium_after](https://user-images.githubusercontent.com/29736082/54078925-7298ff80-42c9-11e9-8b8a-59e928a25d37.PNG)

instead of this

![folium_before](https://user-images.githubusercontent.com/29736082/54078926-7298ff80-42c9-11e9-8563-daa0502c3f5a.PNG)

Right now I have a hacky python script that edits the html file after saving, but it would be great to be able to do this within folium.

API could be like

```python
m.create_pane(name="labels", z_index=625, pointer_events=False)

labels = folium.TileLayer(
    name="extra-labels",
    tiles="https://stamen-tiles-{s}.a.ssl.fastly.net/toner-labels/{z}/{x}/{y}{r}.png",
    attr='Map tiles by <a href="http://stamen.com">Stamen Design</a>, <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a> &mdash; Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
    overlay=True,
    show=True,
    pane="labels",  # This already gets passed through
).add_to(m)
```

If this sounds possible, I'd be happy to take a crack at implementing it.

Cheers,
Liam

**Comment by ocefpaf** [comment]
Sure. That would be a nice addition if you are willing to put a PR together.

**Comment by Conengmo** [comment]
Nice idea Liam! Though I'm wondering how we can do this sensibly. I'm thinking it would be nice if we don't have to add a `panes` argument to every class. Unfortunately it seems the Leaflet classes don't have a `setPane` method or something. Or do they? Otherwise, each folium class would need to pass on `**kwargs` as options.

You mention a `Map.create_pane` method. Currently nearly all folium functionality is in classes that are added to each other. What do you think of a `Pane` class that can be added to a `Map`?

Anyway, sounds interesting if you want to open a PR for this! I do think this functionality would warrant its own example notebook, so would be great if you could include that.

**Comment by lpkirwin** [comment]
Thanks both, how about an API more like

```python
folium.CustomPane(name="labels", z_index=625, pointer_events=False).add_to(m)
labels = folium.TileLayer(...).add_to(m, custom_pane="labels")
```

(I haven't yet looked under the hood at folium, so maybe something else will seem better as I go along...)
