### ISSUE TITLE
GeoJson make zoom on click optional

### ISSUE THREAD

**Issue by limi44** [python-visualization/folium#1162]
The default behavior when clicking on a region (e.g. a state) appears to have changed in version 0.9.1 compared to 0.8.3. On click in 0.9.1, the map zooms in close to the region. In 0.8.3, there is no zoom on click. This can be replicated using the choropleth sample code from the quickstart: https://python-visualization.github.io/folium/quickstart.html.

```python
import folium
import pandas as pd


url = 'https://raw.githubusercontent.com/python-visualization/folium/master/examples/data'
state_geo = f'{url}/us-states.json'
state_unemployment = f'{url}/US_Unemployment_Oct2012.csv'
state_data = pd.read_csv(state_unemployment)

m = folium.Map(location=[48, -102], zoom_start=3)

folium.Choropleth(
    geo_data=state_geo,
    name='choropleth',
    data=state_data,
    columns=['State', 'Unemployment'],
    key_on='feature.id',
    fill_color='YlGn',
    fill_opacity=0.7,
    line_opacity=0.2,
    legend_name='Unemployment Rate (%)'
).add_to(m)

folium.LayerControl().add_to(m)

m
```
This occurs for folium.GeoJson as well. Is there an option to disable this zoom?

**Comment by Conengmo** [comment]
I dont know from the top of my head but it seems possible that this is the case, there have been some changes.

Can you say what the use case is for disabling this behavior? Knowing that will help decide if and how we want to resolve this.

**Comment by limi44** [comment]
In my use case, I have pop-ups for each region that appear on click, so after clicking once, I'm forced to zoom back out to click another region.

As a default behavior, this doesn't seem very useful for Choropleth as you're not getting more information by zooming in.

**Comment by fullonic** [comment]
This issue is related with this feature of geojson class:
https://github.com/python-visualization/folium/blob/f05f3ce9b3d71f87a0738f3c8c1236b933e497a9/folium/features.py#L411-L413

We could make it optional by adding a boolean parameter and make it deactivated by default when a geojson layer is created through the Choropleth class. 

GeoJson class template:
```
 {% if this.zoom_on_click %}
 click: function(e) {
     {{ this.parent_map.get_name() }}.fitBounds(e.target.getBounds());
 }
 {% endif %}

```

The default value could be `zoom_on_click=True` when working directly with geojson class so we don't need to pass a extra parameter to have this functionality. However, when working with choropleth class the default value would be `zoom_on_click=False` and passed to the geojson class when the layer is created:
https://github.com/python-visualization/folium/blob/f05f3ce9b3d71f87a0738f3c8c1236b933e497a9/folium/features.py#L1152-L1156

In this way we could keep the default behavior of choropleth maps as before, but give to the user the possibility to add this feature (fit bounds on click) if she/he wants.

@Conengmo what do you think?

**Comment by nicktsad** [comment]
Hello,
regarding the above, I have the same issue and I could not figure out how to disable zoom when clicking on a geojason polygon. So in my case, I have several polygons with pop up in each polygon and when I click to see the details of each polygon it zooms in a lot and I have to zoom out in order to go and click another polygon. Is there a way to disable this functionality? Thanks

**Comment by Conengmo** [comment]
We did not resolve this issue, I kind of lost track of this discussion. But @fullonic idea sounds good! I agree that in many use cases we don't want to zoom by default. If somebody wants to make a PR with this I'd be happy to review it.

**Comment by datachico** [comment]
I also would love to see the ability to disable the "click to zoom" functionality. Is there at least a way to specify the zoom_level upon the chloropath click?  It creates an awkward experience - the map is at zoom level 13 and it zooms out to level 6 or so.
