### ISSUE TITLE
Rotation on CustomIcon

### ISSUE THREAD

**Issue by yana209** [python-visualization/folium#1187]
#### Please add a code sample or a nbviewer link, copy-pastable if possible

I'm trying to plot sectors of telecom sites (differnt azimuth). The closest way that I could think of was to use CustomIcon option however it dosn't offer angle or rotation option so it's not useful. Azimuth vary so could not use fixed angle symbols. Is there a plan to add this functionality?

```python
# Your code here

```
#### Problem description

[this should explain **why** the current behavior is a problem and what is the expected output.]

**Comment by Conengmo** [comment]
The `CustomIcon` class uses Leaflet's regular `Icon` class under the hood. So any options you see there are available to you: https://leafletjs.com/reference-1.5.0.html#icon

There's no plan to add more functionality. folium is maintained by volunteers, so if you have an idea for an enhancement you are welcome to share it, for example here or by opening a PR.

I'm closing this issue since it's unlikely action will be taken on this. If someone wants to work on this we can reopen of course.
