### ISSUE TITLE
ImageOverlay issues with large .png file

### ISSUE THREAD

**Issue by jpcarnes** [python-visualization/folium#1198]
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```python
img = folium.raster_layers.ImageOverlay(
    name='Mylan Parl',
    image=r'path_to_variable',
    bounds=[[min_lat, min_long], [max_lat, max_long]],
    opacity=0.6,
    interactive=True,
    cross_origin=False,
    zindex=1,)

img.add_to(m)

```
#### Problem description

I am trying to overlay a static .png file to a map using folium. I had the original .tif converted to a .png using rasterio. I also found the bounds using rasterio and stored them in the array above. 

The image I am trying to overlay on the map is 385 mb because it is a very detailed picture of the landscape. Everytime I try running m or m.save('map.html') my computer crashes.

Was running on mac with only 16 gb ram switched to windows with 32 gb ram and it completes the cell in jupyter notebook now but still doesn't populate anything in the map.html file.

Does anyone know how to better handle large images in folium or what issues I may have in my code? Thanks in advance for the help!

**Comment by Conengmo** [comment]
Hi @jpcarnes, it could well be that your image is just *too damn large* :p But let's see if we can do something. Folium converts images to a string it embeds in the html. Maybe you can try to instead use a url and skip the embedding part.

Create a map html file without the `ImageOverlay`, then add the Javascript to the html file manually. I copied it from our [`ImageOverlay` class](https://github.com/python-visualization/folium/blob/master/folium/raster_layers.py#L186). Make sure to fill in your values. Look up the map objects name where `L.map()` is called.

```
L.imageOverlay(
  "/path/to/your/image",
   [[min_lat, min_long], [max_lat, max_long]],  // replace with actual values
).addTo(yourActualMapObject);
```

This way you skip embedding the image, and let Leaflet handle the image directly. Can you check if this improves things?

**Comment by jpcarnes** [comment]
Hi @Conengmo thanks for the swift response! Switching from local path to the url worked !! It took about 10-15 seconds for the full image to render :) 

Stored the photo in aws then hit that url. thanks for the help!!

**Comment by Conengmo** [comment]
Good to hear! 

This issue shows that an obvious improvement to folium would be to add an ‘embed’ option to ImageOverlay, to allow disabling embedding images.

**Comment by amarazov** [comment]
I also experience similar problem. An `embed` option will be helpful.

**Comment by felipetobars** [comment]
Hello, @jpcarnes and @Conengmo .

I have tried to export my .tif file to .png in two ways:
 1. With rasterio reading each band as an array and then combining them to create the image.
2. Using the gdal_translate commands:
    `gdal.Translate('raster_optim.tif', 'raster.tif', creationOptions=["COMPRESS=JPEG", "TILED=YES", "PHOTOMETRIC=YCBCR"])`
    `gdal_translate -OF JPEG -B 1 -B 2 -B 3 raster_optim.tif image_optim.png`

The first method consumes a lot of resources and the second generates a very heavy .png for me to view with folium. (processed rasters range from 5GB to 40GB).

This post discussed how this visualization could be done, modifying the JS code in the HTML and calling the image from an URL, but I have the limitation that I cannot upload that data to a server like AWS due to confidentiality restrictions.
Is there any other way to view these images?

(I tried with simple images both local and Google (URL) and I had no problem)

**Comment by Conengmo** [comment]
Turns out the answer is that `ImageOverlay` already supports not embedding images! But the string provided to the `image` argument has to be a valid url. That means it should start with `https://`, or for local files, `file://`.

That means to use a local file you **don't** want to embed, you should do:

```
img = folium.raster_layers.ImageOverlay(
    image=r'file://C:\myuser\path_to_variable',
    bounds=[[min_lat, min_long], [max_lat, max_long]],
)
```

Note that in that case you can't use the `mercator_project` argument.

Check out the second cell of this notebook for another example: https://nbviewer.org/github/python-visualization/folium/blob/main/examples/ImageOverlay.ipynb
