### ISSUE TITLE
Folim Choropleth issue

### ISSUE THREAD

**Issue by arghyadeepganguly** [python-visualization/folium#1253]
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```python
# Your code here

url = 'https://github.com/datameet/Municipal_Spatial_Data/blob/master/Kolkata/kolkata.geojson'
state_geo = f'{url}'

m = folium.Map(location=[22.568889, 88.346167], zoom_start=3)

m.choropleth(
    geo_data=state_geo,
    name='choropleth',
)

folium.LayerControl().add_to(m)

m
```
#### Problem description

This code is throwing below error

Expecting value: line 7 column 1 (char 6)

#### Expected Output
Choropleth map of Kolkata, India

#### Output of ``folium.__version__``
'0.5.0'

**Comment by Conengmo** [comment]
Hi @arghyadeepganguly, please make sure you are using the latest version of folium. Provide the full error, this information is not enough to help debug this issue.

Since you're only using a geojson without added data, it seems like you should use the `GeoJson` class instead of choropleth.

I'm closing the issue because I'm pretty sure this is not an issue with folium.
