### ISSUE TITLE
WMS Tile Layer as Map - WMS tile layer has no attribute .lower()

### ISSUE THREAD

**Issue by hbxbgrw7913** [python-visualization/folium#1272]
#### Code
```
import folium

atlas = folium.raster_layers.WmsTileLayer(url = 'https://sgx.geodatenzentrum.de/wms_webatlasde.light_grau?', layers='webatlasde.light_grau', name='test', fmt='image/png', attr='test', transparent=True, version='1.3.0')

m = folium.Map(location=['51.133333','10.416667'], tiles=atlas, zoom_start=6)
```
#### Problem description
I try using a WMS tile layer as a map by passing it as a tile to folium.Map. However, it only raises the error 

> "WmsTileLayer' object has no attribute 'lower'"

which I think is because "tiles" in folium.Map only takes strings. It works fine the other way, i.e. first folium.map than add wms tile layer, but I want the tile layer as a map and no other map loaded similarly.

#### Expected Output
folium.Map should take tile layer objects as well

#### Output of ``folium.__version__``
0.10.1

**Comment by Conengmo** [comment]
You're right that the `tiles` argument of `Map` expects a string. That's because it will create a `TileLayer` object with that string. If you don't want a default tilelayer you can disable it like so: `Map(tiles=None)`.

I'm not against changing `Map` to also allow a `TileLayer` or `WmsTileLayer` as argument for `tiles`, since it's a simple change. But if we do that, maybe leave it undocumented, since it's not really Pythonic to have several ways to pass or add tilelayers.

**Comment by Conengmo** [comment]
I'll close the issue because I don't think it's important we take action on this.
