### ISSUE TITLE
Redundant popup_on?

### ISSUE THREAD

**Issue by themiurgo** [python-visualization/folium#131]
What's the reason for having the parameter `popup_on` on features? In which cases is it useful? To me it seems sensible that if a popup text is passed one wants a popup and otherwise it should be off.

At the very least we should enable a popup if text is passed and disable the popup if no text is passed. Provided that it is useful, the parameter can be maintained to force behaviour (for example showing popup when no popup text is passed and, vice versa, hiding even if text is passed).

**Comment by ocefpaf** [comment]
Yes. Makes sense.

Actually, after reviewing one of your PRs recently, I came to the same
conclusion.  Not sure if @robstory had a reason for that design. We can
address that in a PR and keep discussing there.

(I am away from my laptop for while. If want to implement the PR go ahead,
otherwise I can do this once I get back.)
Em 18/05/2015 19:38, "Antonio Lima" <notifications@github.com> escreveu:

**Comment by themiurgo** [comment]
I have a PR handy. :)

**Comment by ocefpaf** [comment]
Thanks!
Em 19/05/2015 11:13, "Antonio Lima" <notifications@github.com> escreveu:
