### ISSUE TITLE
Vega chart into GeoJSonPopup object

### ISSUE THREAD

**Issue by Hpoupon** [python-visualization/folium#1315]
Hello ! I'm a beginner with folium.
I'm looking to implement a Vega graphic in a GeoJsonPopup type object but it doesn't work because "GeoJsonPopup has no attribute 'html". Is it possible to insert graphs in a GeojsonPopup object?

**Comment by Hpoupon** [comment]
Hello ! I'm a beginner with folium.
I'm looking to implement a Vega graphic in a GeoJsonPopup type object but it doesn't work because "GeoJsonPopup" has no HTML object ". Is it possible to insert graphs in a GeojsonPopup object?

**Comment by Conengmo** [comment]
Hi @Hpoupon, I haven't tried it but it should be possible. If you put raw html into you geojson data, you can display that in the popup.

```
with open('tests/us-states.json')) as f:
    geo_json_data = json.load(f)

for feature in geo_json_data['features']:
    feature['properties']['html'] = '<b>hi</b><i>there</i>'

geojson_popup = folium.GeoJsonPopup(
    fields=['html'],
)

geojson_obj = folium.GeoJson(
    geo_json_data,
    popup=geojson_popup,
).add_to(m)
```

But this won't directly work with our current Vega classes. You'll have to prepare the html for each popup yourself.

**Comment by Hpoupon** [comment]
Hi ! Thank you for your help ! I will try this.
Do you have a easy way to save a graph into a html file ?

**Comment by Conengmo** [comment]
You'll have to figure that out for yourself.

By the way, instead of using `GeoJsonPopup` you could consider using our regular `Popup`, which already works well with Vega charts. See [this example notebook](https://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/Popups.ipynb#Vega-Popup). Than it's just a matter of getting the coordinates out of your geojson dictionary and adding the popups to the map (or a feature group).

**Comment by Hpoupon** [comment]
Thanks ! I used `GeoJsonPopup` because I wanted to display a chart when I click anywhere on the polygon.
It works with I prepare the html before. 
Thanks again for your help

**Comment by Conengmo** [comment]
Good to hear :)
