### ISSUE TITLE
Vincent builder does not work on Colab Google

### ISSUE THREAD

**Issue by LaurianoElmiroDuarte** [python-visualization/folium#1335]
Good night everyone, I am following the documentation on the link I am not able to execute the Vincent builder, I import "import vincent" however, when executing I am not successful, I am doing a popup with maps, following the link on this page 'https: // python-visualization .github.io / folium / quickstart.html # Getting-Started 'in out [10 and 11] I'm using google colab.
Do I have to use any repository, extra library?

**Comment by Conengmo** [comment]
I don't see an `import vincent` on that page: https://python-visualization.github.io/folium/quickstart.html

You'd need an extra library, in this case Vincent or Altair (https://github.com/altair-viz/altair), to generate the graphs embedded in the popups. But that's not needed for the example in the quickstart guide, because there the  data is already generated.

**Comment by LaurianoElmiroDuarte** [comment]
Hi @Conengmo , a lib Vincent is out [10] and [11]

I wanted to say that the Vincent library is out of date. 

thank, for your help.
