### ISSUE TITLE
Trouble binding dataframe to GeoJson?

### ISSUE THREAD

**Issue by gavirapp** [python-visualization/folium#1338]
I am new to folium and trying to use it for a choropth map.  Can't get past this error.  I think the problem it in binding my data to the GeoJson file.   Here is the code:

#initialize an empty dataframe to store this new data
ByZip = pd.DataFrame()
#populate the new dataframe with a 'zipcode' column and a 'numStores' column
ByZip['zipcode'] = comb_df['zipcode']
ByZip['population'] = comb_df['population']

#initialize the NY area map
NYMap = folium.Map(location=[40.7597,-73.9841], tiles='Stamen Toner', zoom_start=9)
#draw the choropleth map. These are the key components:
NYMap.choropleth(geo_path = US_MAP_detailed , geo_data = ByZip, \
                 columns=['zipcode', 'population'], key_on='features.properties.ZCTA5CE10', fill_color='YlGn', fill_opacity=0.6)
#NYMap.save('NYChoropleth.html')
NYMap

Keep getting the error: 
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-84-02a12f7cbfb9> in <module>
     23 
     24 NYMap.choropleth(geo_path = US_MAP_detailed , geo_data = ByZip, \
---> 25                  columns=['zipcode', 'population'], key_on='features.properties.ZCTA5CE10', fill_color='YlGn', fill_opacity=0.6)
     26 
     27 #NYMap.save('NYChoropleth.html')
.....
.....
......
    500 
    501     def convert_to_feature_collection(self):

ValueError: Cannot render objects with any missing geometries:           zipcode  population
ZIP_clean                    
01020       01020     29668.0
01082       01082     10322.0
01253       01253       731.0
01602       01602     22819.0

_____________________________

Here is what my python dataframe looks like:
>>>comb_df.head()

	        zipcode	population
ZIP_clean		
01020	01020	29668.0
01082	01082	10322.0
01253	01253	731.0
01602	01602	22819.0
01778	01778	13109.0

And the GeoJson file attibute I am trying to bind to:

>>>US_MAP_detailed['features'][10000]['properties']['ZCTA5CE10']
'10553'

Any sort of help hint will be greatly appreciated.

**Comment by jtbaker** [comment]
@gavirapp check the naming of your keyword arguments, you need to switch geo_path to geo_data (the spatial data), and geo_data to data (the non spatial data).

One other thing I noticed: you have "features" as plural in your `key_on` kwarg; if you look carefully in the docs you'll see that it gets referenced as a singular. This is because it is executing in a loop over all the features in the features list.

Check the docstring in the source code for more information: https://github.com/python-visualization/folium/blob/c8707b167619b8eee69d3e6dd247905a72beab7e/folium/features.py#L1047-L1060
