### ISSUE TITLE
 Choleramap  is not filling the area properly 

### ISSUE THREAD

**Issue by prajwalmani** [python-visualization/folium#1351]
Hey , i did all the things which were stated in the previous issues 
folium version:0.11.0
[geojson :](https://raw.githubusercontent.com/johan/world.geo.json/master/countries.geo.json)
[dataset](https://www.kaggle.com/imdevskp/corona-virus-report) (covid_19_clean_complete.csv)
g is the dataframe for the dataset

`  world_map=folium.Map(zoom_state=1,tiles='Mapbox Bright')
world_geo_path=r'C:\Users\prajw\Downloads\world-countries.json'
folium.Choropleth(
          geo_data=world_geo_path,
          data=g,
          columns=['Country','Confirmed'],
          key_on='feature.properties.name',
          fill_color='YlOrRd',
          legend_name='Covid 19 Confirmed Cases'
).add_to(world_map)
world_map`
please help me debug  i got this kind of map 
![map](https://user-images.githubusercontent.com/56246392/83936786-7d03bb00-a7e4-11ea-965f-33c7c89c3677.PNG)

**Comment by sackh** [comment]
There is an issue with your CSV data and GeoJSON:
`Country/Region` column is not matching with `feature.properties.name` for some countries.
E.g. United States is gray because in your GeoJSON name in properties is `United States of 
America` and in your CSV `Country/Region` name is `US`.

Apart from this, there are duplicate values for countries in your CSV e.g. `china`, you will have to clean the data before creating choropleth.

**Comment by Conengmo** [comment]
Thanks for helping here @sackh, I'll close the issue since this is not an issue with folium
