### ISSUE TITLE
Get zoom level of a map object

### ISSUE THREAD

**Issue by NatalieThurlby** [python-visualization/folium#1352]
I wanted to set the `min_zoom` of the map to the same level of zoom that's calculated by `fit_bounds`, but I can't figure out how to extract the zoom level from the map object. I see that leaflet has a `getZoom()` function, so I was wondering if that could be used.

I ended up doing this by trial and error and the zoom level came out as 10. Is that just a weird coincidence, or is it something to do with how the zoom level is defined?

**Comment by Conengmo** [comment]
I suppose the zoom level was indeed 10 at that time. Is that weird?

Since you already figured out how to use the `getZoom()` method, what else is there to say? I don't really see this as a permanent feature of folium, so I'll close the issue. If there is a compelling use case we can reopen the issue of course.
