### ISSUE TITLE
Adjusting leaflet legend colors/values dynamically with python

### ISSUE THREAD

**Issue by Siliconrob** [python-visualization/folium#1357]
**Adjusting leaflet legend colors/values dynamically with python**

I am having trouble trying to dynamically adjust or set the legend for a folium map.  In the situation you have multiple layers that are constructed from the `macro` element.

[Here](https://github.com/mrcagney/examples_folium/blob/develop/notebooks/categorical_legend.ipynb) is an example of someone trying to inject the javascript of the legend dynamically 

The alternative is to use Javascript to lookup the elements and find the data within the geojson layer and compute the color and values and then do DOM manipulation of the legend elements through raw javascript.  Problem in that situation is that I don't know a nice way to lock in the DOM element ids for the generated python macro function and or how can I inject a specific javascript click type event that will reference the dynamically generated element ids.

Some pointers on how to build this out and or if there is a way to construct JavaScript event handlers attached to particular leaflet standard controls like LayerControl or Legend

**Comment by Conengmo** [comment]
Hi @Siliconrob, on the Python side you can get the names the objects will have on the JS side with the `get_name()` method. Don't know if that's what you're looking for? Other than that you're pretty much on your own I'm afraid.

Since folium is a library to manipulate and use your data in Python, I don't think we should have functionality that does this in JS instead. I'm not against categorical legends per se, but if we do that they should be generated on the Python side.
