### ISSUE TITLE
Adding IFrame or Script Capability to GeoJsonPopup

### ISSUE THREAD

**Issue by Tyllis0** [python-visualization/folium#1362]
Currently you can embed a IFrame to Popup. This opens up a lot of possibilities for the popups. For example, you can create interactive visualizations via libraries such as Plotly, retrieve the html code and embed in a IFrame, which can then be added to the map as popups.

This capability does not seem to work with GeoJsonPopup. GeoJsonPopup seems to only read plain text or plain html. Is it possible to have GeoJsonPopup recognize IFrame object or html with javascript in the "fields" of geojson "properties"?

**Comment by joaopalotti** [comment]
I am currently with the same question. Any updates @junyan0?

**Comment by Tyllis** [comment]
I found a work around with plotly. Use plotly.offline.plot function to turn the interactive plot into html. Then you stuff that into this function:
def plot_to_iframe(plot, width, height):
    html_string = '''
        <html>
            <head>
              <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
            </head>
            <body>
              ''' + plot + '''
            </body>
        </html>'''
    iframe = folium.IFrame(html_string, width=width, height=height)
    return iframe

Then you turn that into a folium popup: folium.Popup(iframe).

**Comment by joaopalotti** [comment]
Hi Tyllis, 

Thanks for your quick reply! What I was curious about was how to use GeoJsonPopup with custom HTML. 
I think what you are describing is swapping GeoJsonPopoup with Popup, but I am not sure if you would be able to have multiple popups, e.g., one for each location of your GeoJson.

After some try-and-errors, I think I found a solution to my problem that worked well.
My code is heavily based on [this folium tutorial notebook](https://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/GeoJsonPopupAndTooltip.ipynb), but instead of only showing a given dataframe column as a pre-defined HTML table, as the tutorial does, I created a new col with my HTML code and displayed only it. 
I am sharing some snippets below to help whoever has the same problem in the future:

```python

#  .... some code to get the df as in the tutorial

def getHTML(row):
   return "<b> Place: %s </b>" % row["name"]

df["html_to_display"] = df.apply(getHTML, axis=1)

# ...
popup = GeoJsonPopup(
   # Replaced fields and aliases with my own 'html_to_dsplay' 
   #fields=["name", "medianincome", "change"],
    #aliases=["State:", "2015 Median Income(USD):", "Median % Change:"],
    #labels=True,
    labels= False, fields = ["html_to_display"],
    localize=True,
    style="background-color: yellow;",
)

g = folium.GeoJson(
    df,
    popup=popup
).add_to(m)
```

**Comment by tarynblack** [comment]
@joaopalotti this was exactly what I needed, thank you!
