### ISSUE TITLE
TimestampedGeoJson with features of different durations

### ISSUE THREAD

**Issue by Pitirus** [python-visualization/folium#1364]
I would like to create an animation using `TimestampedGeoJson` with multiple features (e.g. LineStrings) that have different durations.

Currently, all features need to have the same duration defined using `duration` parameter from `TimestampedGeoJson` constructor.

Has anyone achieved such a thing?
If no I would like to request such a feature.

**Comment by Conengmo** [comment]
You could check out the underlying JS library we use for this: https://github.com/socib/Leaflet.TimeDimension. See if they support it.

I'll close the issue because it's not something that's really within scope. If somebody does figure it out, please report back here to share it with others. We might consider a PR if the change is simple enough.
