### ISSUE TITLE
Choropleth Map - Folium Data Won't Show

### ISSUE THREAD

**Issue by grantbriana** [python-visualization/folium#1366]
```python
# Your code here
import folium
import pandas as pd

address = 'Columbus, GA'

geolocator = Nominatim(user_agent="ga_explorer")
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude
print('The geograpical coordinate of Columbus, GA are {}, {}.'.format(latitude, longitude))


df = pd.read_csv(r'C:\Users\Jill\Downloads\Income__by_Zip_Code__2018_River_valley.csv', usecols=('PlanningRegion','GEOID','aMeanHHIncome_e18','TotPop_e18'), encoding='utf-8')
zip_data = "https://opendata.arcgis.com/datasets/c917469836c2472e9b80ec0b57a24468_111.geojson?where=PlanningRegion%20%3D%20'River%20Valley'%20AND%20%20(GEOID%20%3D%20'31820'%20OR%20GEOID%20%3D%20'31901'%20OR%20GEOID%20%3D%20'31903'%20OR%20GEOID%20%3D%20'31904'%20OR%20GEOID%20%3D%20'31906'%20OR%20GEOID%20%3D%20'31907'%20OR%20GEOID%20%3D%20'31909')%20"
df=df.drop([0,1,2,3,4,5,7,8,9,10,12,13,14,19,20,21,22,23,24,25,26,27,28,30])

map_columbus = folium.Map(location=[latitude, longitude], zoom_start=10)

map_columbus.choropleth(
    geo_data=zip_data,
    data=df,
    columns=['GEOID','aMeanHHIncome_e18'],
    key_on='feature.properties.id',
    fill_color='YlGnBu', 
    fill_opacity=1, 
    line_opacity=1,
    legend_name='Average Household Income',
    smooth_factor=0)

folium.LayerControl().add_to(map_columbus)
# display map
map_columbus
```
#### Problem description
I'm experiencing an issue while creating a folium choropleth map in jupyter notebook. Everything is showing as expected except the data that should be in the map. Instead, the geodata is left blank, not filled with color. 

![pasted image 0](https://user-images.githubusercontent.com/66385889/86986656-2b8f7880-c162-11ea-908e-41d75d4c2600.png)

**Comment by markhudson42** [comment]
Hi,

Could you provide samples of the data that you are using? i.e. the data that you read into the df dataframe and the data that you are reading from the opendata.arcgis.com address?

Mark.

**Comment by markhudson42** [comment]
Hello,

I have reconstructed your example by downloading the ArcGIS JSON file manually and reading it from a local folder, and creating a dataframe of income data by reading it from the JSON itself.

I believe that the cause of your issue is that in your code you have written:

```python
    key_on='feature.properties.id',
```
but what you need is:

```python
    key_on='feature.properties.GEOID',
```

because in the downloaded geojson file, the data appear as follows:

```
{
"type": "FeatureCollection",
"name": "Economic_Income_ZCTA_ACS2018",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "OBJECTID": 72, "PlanningRegion": "River Valley", "ARCModelingArea": "No", "GEOID": "31820",  
```
and so on.

by making this change in my own version of your code (in which I have to create the `df` dataframe because I do not have your data file) I get the following result:

![image](https://user-images.githubusercontent.com/17765609/90548236-8ca86400-e184-11ea-8d38-dab0739f4b74.png)

I also updated your use of Choropleth to avoid the deprecated method, but I do not think this had anything to do with your initial problem:

```python
map_columbus = folium.Map(location=[latitude, longitude], zoom_start=10)

folium.Choropleth(
    geo_data=json_data_file,
    data=df,
    columns=['GEOID','aMeanHHIncome_e18'],
    key_on='feature.properties.GEOID',
    fill_color='YlGnBu', 
    fill_opacity=1, 
    line_opacity=1,
    legend_name='Average Household Income',
    smooth_factor=0).add_to(map_columbus)

folium.LayerControl().add_to(map_columbus)

# display map
map_columbus
```

I hope this helps.

Mark.

**Comment by grantbriana** [comment]
Sorry for the late reply. But thank you so much for your help. I appreciate
it.
