### ISSUE TITLE
Edit markers or import method for Draw plugin

### ISSUE THREAD

**Issue by pepeto** [python-visualization/folium#1378]
**Is your feature request related to a problem? Please describe.**
I have a map with many markers already made programmatically from a database. 

**Describe the solution you'd like**
Be able to edit 'somehow' and delete or add a marker and the be able to process that new points in the program

**Describe alternatives you've considered**
I tried to use Draw but the export button does not allow me to save the old points, just the markers made with the draw plugin.

**Additional context**
It doesn't matter if the communication is via a file or with an "import" button/method. In that way, I can call the "import" and load the waypoints.

THANK YOU!

**Implementation**
folium is maintained by volunteers. Can you help make a PR if we want to implement this feature?

**Comment by Conengmo** [comment]
Hi @pepeto, unfortunately I don't think there's a way to do this with folium. You see, folium is built as a one way street from Python to Javascript (Leaflet). So it's not really designed to get data back from your map into Python.

Some ideas to maybe help you further:
- I was gonna say the `Draw` plugin but you already found it :)
- Maybe ipyleaflet? It's a Jupyter Notebook extension that does maps and has more interactivity than folium.
- Otherwise you would have to go into Javascript code to do this. Look at the html file that folium creates, check the Javascript code in there and look how Leaflet works.

I'm closing this issue since it's out of scope for folium. If there's an easy thing we can do though to make this possible we can discuss it.
