### ISSUE TITLE
bivariate choropleth map

### ISSUE THREAD

**Issue by hishamsajid** [python-visualization/folium#1397]
Could we have bivariate choropleth maps? I don't there's any python visualization library out there which has this feature. 

**What is a bivariate choropleth?**

basically  [this](https://www.joshuastevens.net/cartography/make-a-bivariate-choropleth-map/)

![image](https://user-images.githubusercontent.com/22274436/96243654-75d49100-0fbe-11eb-9d14-b52614775030.png)

Closest thing I can find to this is an implementation by some user in plot.ly [here](https://chart-studio.plotly.com/~empet/15354/plotly-choropleth-from-shapefiles/#/)

**Comment by Conengmo** [comment]
This should be possible, but require some data wrangling. See this guide on how to create choropleths with folium: https://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/GeoJSON_and_choropleth.ipynb Read up until "Using Choropleth class". I don't think you can use the `Choropleth` class itself, because that is too specific. Instead use the `GeoJson` class with custom `style_function`.

I don't have ideas for creating that legend. Maybe make some custom html+css+JS and add that. Or just add it as a figure. folium doesn't really have things for making a legend like that.

I'm going to close this issue because it's not something I think needs change on folium. If you do have ideas, lets hear them and we can reopen if needed. If you make this work, a PR with an example notebook is much appreciated.

**Comment by engmubarak48** [comment]
@Conengmo this link is not working, may be share the code snippet or link available. And also this is closed, is their a way to do with folium with legends.

**Comment by r-leyshon** [comment]
Would be a great feature if `folium.GeoJson` could accept a list of 2 columns for  `fillColor` and return an equivalent to OPs example.
