### ISSUE TITLE
What is the limit/load for the html page created??

### ISSUE THREAD

**Issue by gmehta1996** [python-visualization/folium#1399]
I have plotted around 1.5 lakh markers with some text on the tooltip and I have generated an html page of 135 MB . But this page is not being opened on any browser. It is showing a blank white page and does not load. Is there a limit in this or is there a way to load a huge html page with a lot of markers with their text as well???

Following is my code:
I am getting the data into variables from MongoDB 

```
cord = [lat , long]

feature_group = folium.FeatureGroup(name='Data')
my_map = folium.Map(location = cord,zoom_start=5)


feature_group.add_to(my_map)
folium.LayerControl().add_to(my_map)

for i in collection1.find():
	state = i.get('State')
	district = i.get('District')
	pincode = i.get('Pincode')
	lat = float(i.get('Latitude'))
	lon = float(i.get('Longitude'))
    
        location = [lat,lon]
	html1 = f'''<h6> {state} <h6>
		         <h5> {district} <h5>
		         <h5> <b>Pincode : <b> {pincode} <h5>'''

	folium.Marker(location, tooltip=html1,icon=folium.Icon(color='blue',icon = 'fa-home', prefix='fa')).add_to(feature_group)

my_map.add_child(feature_group)

my_map.save(r'Address.html')
```

**Comment by Conengmo** [comment]
I don't think there's a hard limit in size, but as you experienced it can become slow to load a lot of markers.

Check out the `MarkerCluster` class, which is meant to accomodate a lot of markers. There's also `FastMarkerCluster`, which should work with even bigger datasets. Both are described, with examples, in: https://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/MarkerCluster.ipynb

I hope that should be enough for you. I'm closing this issue since I don't think there's any work to be done on folium for this. If there is, let us know what and we can reopen.

**Comment by gmehta1996** [comment]
I reduced the data to 10K markers and the html got loaded in the browser but the same is not being opened when markers are more

**Comment by gmehta1996** [comment]
Hi, I would appreciate if you could help me with this issue. I tried to plot around 150K latitude longitude using markers but there seems to be an issue with the html page being generated. It shows a blank white page and does not get loaded. But the same gets loaded when the lat long data is reduced to 14-15K .Shall I share the html page once for you to view the issue??

**Comment by Conengmo** [comment]
Did you try the `MarkerCluster` or `FastMarkerCluster`? There are performance limits with Leaflet, so we'll just have to deal with that.

**Comment by gmehta1996** [comment]
Yes I did try it..still did not work.
So is it not possible to plot millions of markers on the map using folium?
Is there no solution for it???
