### ISSUE TITLE
Getting the coordinate of the Marker created with ClickForMarker

### ISSUE THREAD

**Issue by baspinarenes** [python-visualization/folium#1446]
I want to write a program that records in Python list the coordinate of the point I clicked on the Folium map. However, I could not find how to access marker. It is written that this feature is not available. Any improvement?

**Comment by fullonic** [comment]
Hey @baspinarenes. That isn't possible to achieve with folium as it is. And the main reason is because folium is 'made' to get python data and convert it to be displayed on a leaflet map. Once you do `map.save()`, for example, you can't get data back to python.

However there are two things that you may do to get what do you need:
- Using the [Draw plugin](https://python-visualization.github.io/folium/plugins.html#folium.plugins.Draw), which allows you draw markers and export their position it as a json file. If a json file is enough, great, you are done. Otherwise, If you really need the markers as a python list, you will need a python webserver where you can send the information. To do so, you need to write some costume javascript that gets the json data generated by the the Draw plugin and send it to your server.
- The second possibility, is write a costume javascript data collects your map clicks, generate an array, converts it to json object, and send it back to python. However, even is this scenario, you will a webserver to receive your data from the map.

There is a example of how run folium with flask, you can see it [here](https://python-visualization.github.io/folium/flask.html). If you don't know [flask](https://flask.palletsprojects.com/en/1.1.x/), it's a python webserver that is very easy to start with.

**Comment by baspinarenes** [comment]
> Hey @baspinarenes. That isn't possible to achieve with folium as it is. And the main reason is because folium is 'made' to get python data and convert it to be displayed on a leaflet map. Once you do `map.save()`, for example, you can't get data back to python.
> 
> However there are two things that you may do to get what do you need:
> 
>     * Using the [Draw plugin](https://python-visualization.github.io/folium/plugins.html#folium.plugins.Draw), which allows you draw markers and export their position it as a json file. If a json file is enough, great, you are done. Otherwise, If you really need the markers as a python list, you will need a python webserver where you can send the information. To do so, you need to write some costume javascript that gets the json data generated by the the Draw plugin and send it to your server.
> 
>     * The second possibility, is write a costume javascript data collects your map clicks, generate an array, converts it to json object, and send it back to python. However, even is this scenario, you will a webserver to receive your data from the map.
> 
> 
> There is a example of how run folium with flask, you can see it [here](https://python-visualization.github.io/folium/flask.html). If you don't know [flask](https://flask.palletsprojects.com/en/1.1.x/), it's a python webserver that is very easy to start with.

Thank you very much for your information. I will investigate what you said.
