### ISSUE TITLE
Plotting Image on Folium Maps masking nodata values

### ISSUE THREAD

**Issue by rrsc1234** [python-visualization/folium#1470]
Hi. I am using the following code to display RGB (.tif) image on the folium map:
```python
import rasterio as rio
import folium
from pyproj import Transformer 

## LC08 RGB Image
in_path = 'RGB.TIF'

dst_crs = 'EPSG:4326'

with rio.open(in_path) as src:
    
    img = src.read()
        
    src_crs = src.crs['init'].upper()
    min_lon, min_lat, max_lon, max_lat = src.bounds
    
## Conversion from UTM to WGS84 CRS
bounds_orig = [[min_lat, min_lon], [max_lat, max_lon]]

bounds_fin = []
 
for item in bounds_orig:   
    #converting to lat/lon
    lat = item[0]
    lon = item[1]
    
    proj = Transformer.from_crs(int(src_crs.split(":")[1]), int(dst_crs.split(":")[1]), always_xy=True)

    lon_n, lat_n = proj.transform(lon, lat)
    
    bounds_fin.append([lat_n, lon_n])

# Finding the centre latitude & longitude    
centre_lon = bounds_fin[0][1] + (bounds_fin[1][1] - bounds_fin[0][1])/2
centre_lat = bounds_fin[0][0] + (bounds_fin[1][0] - bounds_fin[0][0])/2

m = folium.Map(location=[centre_lat, centre_lon],
                   tiles='Stamen Terrain', zoom_start = 10)

# Overlay raster (RGB) called img using add_child() function (opacity and bounding box set)
m.add_child(folium.raster_layers.ImageOverlay(img.transpose(1, 2, 0), opacity=.7, 
                                 bounds = bounds_fin))

# Display map 
m

```
After running the above code the image is getting displayed on the map but my issue is how to remove or mask nodata values from the image displayed on the map.

####
![folium](https://user-images.githubusercontent.com/54926076/115021719-f4f94200-9ed9-11eb-8538-3de2f166eeb6.jpg)

Can someone tell how to solve it.

My ``folium.__version__`` is "0.12.1"

**Comment by HarshitaMav** [comment]
with rio.open(geotiff_geo) as src:
    boundary = src.bounds
    img = src.read(1)
    nodata = src.nodata  
   
img[img==nodata] = np.nan


Try running this code this may work

**Comment by juanmorysson** [comment]
@rrsc1234 Did you manage to solve it?

**Comment by Conengmo** [comment]
I can't really help you further I'm afraid. If somebody wants to dive into this, it's very welcome. I'll close this issue, since it's stale. Further input is welcome though.

**Comment by anjishnum** [comment]
Hello,

I think I may have found the solution.

I was working on this exact same thing with a circular bound instead of a rectangular one as follows:

![with_nodata_img](https://user-images.githubusercontent.com/35238072/228878748-24ce180d-077a-4f5c-b0aa-5c504cb75e82.PNG)

My image had a shape of (3, 2004, 2044). What I first did was create another array of shape (2004, 2044) as the alpha channel. Then for every pixel in the image having a value of 0 in each of the RGB channels, I converted the corresponding value in the alpha channel to 0 and kept the rest of the values as 1. Then I appended the alpha channel to the RGB channel to create an RGBA numpy array.

Also while reading the tif file, I saved the metadata such as transform, bounds, crs and other parameters in variables with the same names.

After adding the alpha channel to get the rgba image numpy array, all I had to do was save it to a new tif file.

```
import numpy as np
import rasterio as rio

with rio.open(path_to_tif_file) as src: 
    rgb_img = src.read()

    # Get the geotransform and bounding box information
    transform = src.transform
    bounds = src.bounds

    # Get the coordinate reference system (CRS) information
    crs = src.crs

    # Get the nodata value
    nodata = src.nodata

    # Get the number of bands, height, and width of the geotiff file
    count = src.count
    height = src.height
    width = src.width

def add_alpha(rgb_img):
  alpha_channel = np.ones((rgb_img.shape[1], rgb_img.shape[2]))  # create a new alpha channel of shape (2004, 2044) with all values set to 1
  alpha_channel[(rgb_img[0] == 0) & (rgb_img[1] == 0) & (rgb_img[2] == 0)] = 0 # set alpha values to 0 for pixels where all RGB values are 0
  rgba_image = np.concatenate((rgb_img, alpha_channel[np.newaxis, :, :]), axis=0) # concatenate the alpha channel with the RGB image along the first dimension to create a RGBA image
  return rgba_image

rgba_image = add_alpha(rgb_img)

with rio.open(
    output_path,
    'w',
    driver='GTiff',
    height=height,
    width=width,
    count=count,
    dtype=rgba_image.dtype,
    transform=transform
) as dst:
    # Write the NumPy array to the rasterio dataset
    dst.crs = rio.crs.CRS.from_epsg(4326)
    dst.write(rgba_image)
```

After saving the new file, I used this new image in place of the old one for the folium code, and it worked perfectly.
The result being the following:

![without_nodata_img](https://user-images.githubusercontent.com/35238072/228886242-f37e82df-3573-4c9c-875a-8540bc152845.PNG)

The only drawback of adding an extra channel was that it increased the image size from 4MB to 125MB.

Hope it helps 🙂

**Comment by giswqs** [comment]
@anjishnum Leafmap support loading raster datasets with only one line code. 
https://leafmap.org/notebooks/03_cog_stac/
https://leafmap.org/notebooks/32_local_tile/
