### ISSUE TITLE
Closing a Popup when zooming out or preventing it from changing size 

### ISSUE THREAD

**Issue by RaikohGrass** [python-visualization/folium#1494]
Right now I am doing a map of my country with popups including html code that show a wordcloud with random info (for now).
My problem is that when I zoom out to click on another polygon the currently opened popup gets bigger and prevents me from looking at the other polygons: 

![DS4A_Dashboard2](https://user-images.githubusercontent.com/83981857/128359817-9988672f-8eb2-4672-99e5-79aaa4e1b258.gif)

Is there a way I can make the current popup to close when I zoom out?

Maybe preventing the popup from getting bigger would also work.

**Comment by Conengmo** [comment]
The popup stays the same size relative to your window size. I don't know whether it's possible to make it relative to map zoom level, but that does sound problematic, because then the popup content becomes hard to read in the extremes.

The behavior you describe is currently not included in folium. To get that, you would have to work on the underlying Javascript that uses Leaflet.

I don't think this is a feature we'll include in the future so I'll close this ticket. But feel free to discuss the issue here further.

**Comment by RaikohGrass** [comment]
Thanks for your quick answer!
Mmmmm bummer
Sadly I have not worked with Javascript that much.

Is it possible to include javascript functions/code to my map using python?

I tried to include a function in the 'html'-code of my popup but that didnt seem to work:
"""<p><img id="disp" src="xxxxx.png" ></p><script>setTimeout(function(){ var msg = document.getElementById("disp");msg.style.display='none';}, 2000);</script>"""
