### ISSUE TITLE
Adding a GeoJson tooltip to TimeSliderChoropleth

### ISSUE THREAD

**Issue by rodrigoalatorre** [python-visualization/folium#1561]
I've been working with some timeseries data using TimeSliderChoropleth, however, I've found that, while one can add a simple, statis tooltip to the map (via TimeSliderChoropleth.add_child(folium.features.Tooltip(str))), I've been struggling to figure a way to add a tooltip which displays some of the GeoJson's features. 
I've been reading up on how Folium renders GeoJson tooltips and that got me to line 912 on features.py. where the render function inside the GeoJsonDetail is defined. Here, we hace an if statement which checks whether the parent we are trying to add the child to is either a GeoJson or a TopoJson object. 
As far as I see, however, the object produced by TimeSliderChoropleth class, is also a GeoJson and has most of the information required by render()
My naïve solution (adding an additional elif statemtn allowing the parent to be an instance of folium.plugins.TimeSliderChoropleth) seems to be missing the point. Can anyone think of a solution? It feels as if it should be pretty straightforward, but I may also be completely wrong.

Cheers :))

**Comment by joaoambiente** [comment]
This would allow folium to have similar functionality to the one observed in the plotly map at the bottom of this page:
https://amaral.northwestern.edu/blog/step-step-how-plot-map-slider-represent-time-evolu

**Comment by Conengmo** [comment]
I understand the idea, and if someone wants to look into it, that's welcome. I will say I'm not sure if we would include such a change in folium. The `TimeSliderChoropleth` class is pretty fragile as is, I'm afraid to expand it further, making it even less robust. That's why I'll close the issue.

If somebody could do it in a sensible way, yes please. What's very welcome in any case if you can share your work in a gist or your own repo. That way others can use it as well!
