### ISSUE TITLE
Export a draw circle

### ISSUE THREAD

**Issue by giswqs** [python-visualization/folium#1565]
This exported geojson of a circle has only one point. Should there be a radius in the output geojson?

```python
import folium
import folium.plugins as plugins

m = folium.Map()
plugins.Draw(export=True).add_to(m)
m
```
![folium](https://user-images.githubusercontent.com/5016453/150208760-5f3ec546-728f-46c9-a4b5-b916ba50fe3e.gif)

**Comment by NickkRodriguez** [comment]
I would love to solve this issue for you @giswqs.  Can I be assigned to this issue?

**Comment by NickkRodriguez** [comment]
@Conengmo I'm having some issues solving this problem. **Could you or other contributors offer some guidance?** This is one of my first contributions, and I would like to keep contributing to Folium.

I understand that in the plugin Draw, Folium uses Leaflet's own Draw, but Leaflet's documentation doesn't contain attributes for the radius so I'm not sure that's the right way to tackle this unless I bring in new libraries. Maybe I could use the radius that shows up on the screen when making a circle, but I can't find a way to capture that.
 
**Any other ideas?**

**Which files should I be working with?**

I thought instead of making a plugin, it would be best to add/change code from existing files. Whatever works and is more efficient.

If there's a way to privately message, I would appreciate that even more.

Thank you.

**Comment by alessioarena** [comment]
I think this is related https://github.com/Leaflet/Leaflet.draw/issues/551
Also, see this https://gis.stackexchange.com/questions/285352/how-to-get-the-exact-circle-that-user-has-drawn-using-leaflet-draw-circle

Bottom line is that GeoJSON standard does not have a Circle

**Comment by Conengmo** [comment]
Thanks @alessioarena! Unfortunately not much we can do about it. If new information comes up do please share here.
