### ISSUE TITLE
Leaflet.Control.Layers.Tree as a plugin in folium

### ISSUE THREAD

**Issue by vizsim** [python-visualization/folium#1606]
I would love to see Leaflet.Control.Layers.Tree as a plugin in folium!
https://github.com/jjimenezshaw/Leaflet.Control.Layers.Tree

It would boost the ability to interact with mulit-layered data maps created by folium.

Nice example:
https://jjimenezshaw.github.io/Leaflet.Control.Layers.Tree/examples/airports.html 

![grafik](https://user-images.githubusercontent.com/16351144/177002100-97233c94-de10-4f64-a151-f5b5e09a5551.png)

**Comment by IndigoWizard** [comment]
This PR [ #1592 : "add groupedlayercontrol plugin"](https://github.com/python-visualization/folium/pull/1592) is the closest thing to the feature so far, which comes in response to the [issue #1025 : "Radio control instead of checkboxs for layer control"](https://github.com/python-visualization/folium/issues/1025) that requests something like Leaflet plugin [leaflet-groupedlayercontrol](https://github.com/ismyrnow/leaflet-groupedlayercontrol), but it seems it's been hanging there with no new reviews or checks for merge.

**Comment by Conengmo** [comment]
https://github.com/python-visualization/folium/pull/1592 was merged and will be included in the 0.14.0 release. It doesn't contain functionality for layer control trees, so we can keep this issue open.

**Comment by hansthen** [comment]
@Conengmo I can take a stab at porting this plugin to Folium. I used it in another project and I am very fond of it. The main issue that I see in porting it is that `Leaflet.Control.Layers.Tree` is configured through a javascript dictionary with functions at arbitrary locations in the tree. 

Can I pillage your `to_javascript` filter from the draft PR in https://github.com/python-visualization/folium/pull/1856?
