### ISSUE TITLE
Closember participation

### ISSUE THREAD

**Issue by ocefpaf** [python-visualization/folium#1638]
@Conengmo what do you think? Take a look at https://closember.org/ and let me know.

I believe there are some stale PRs, already resolved or no longer relevant issues that could use a clean-up!

**Comment by Conengmo** [comment]
Love it! We could definitely use some cleaning up, and merging good PRs we got waiting. Setting a goal for this month sounds like a good idea to gain some momentum. And fortunately I have some time to spend as well.

Three things we could focus on:
- Get through the backlog of PRs
- Close more issues
- Work on open issues

### PRs

- We mark our participation in Closember.
- Review PR's that look promising.
- Close stale PR's that don't offer much value. (Shortly explain why and what would be avenues for reopening)

### Issues

I'm not sure about closing old issues. I think many of them are still valid, it's more that what they propose is not getting done. Maybe it's a good idea to close them since they didn't get traction, and offer anybody that reads the closed issue to reopen if they are actually able to work on it.

### Open issues

To be done: a shortlist of what would be good to have done first.

**Comment by Conengmo** [comment]
# How users can help

## Close your own stale issues or PRs

If you have an open issue or PR on this repo that you don't support anymore, you can close it yourself. Please include a closing message with a (one sentence) explanation.

## Test open PR's

Look at the open PR's, pick one you are interested in, pull that code and test any or all of the following:
- first verify the problem the PR solves
- test the PR solves the problem
- identify possible side effects or downsides
- identify if the implementation could/should be better

**Comment by Conengmo** [comment]
## Ambitions

- Close all open PRs from before November on folium and branca.

Should we have a goal for the number of open issues? Say, reduce them in half?

**Comment by Conengmo** [comment]
Look at that, no open issues or PRs on branca 🎉

**Comment by Conengmo** [comment]
Branca got a mention from the closember twitter account: https://nitter.net/ClosemberDev/status/1589522298742128641#m

**Comment by Conengmo** [comment]
I also liked this message, congratulating us with reaching zero on branca and 27 closed PRs on folium: https://nitter.net/ClosemberDev/status/1590774786745307136#m

**Comment by ocefpaf** [comment]
We should schedule a call for a virtual toast to celebrate Closember ;-p

**Comment by Conengmo** [comment]
We have the most closed PRs on the board, which is a nice reflection of the amount of work we did!

https://nitter.net/ClosemberDev/status/1592651419059789824#m

![afbeelding](https://user-images.githubusercontent.com/33519926/202478050-022c583a-a860-4f6a-ad4d-946a5c2e003e.png)

**Comment by ocefpaf** [comment]
> which is a nice reflection of the amount of work we did!

You mean you did! I'm pretty much watching from the sidelines. Thanks for the effort you put into this!! We need a new release soon to ship all the new features and bugfixes.

**Comment by Conengmo** [comment]
Well we made the top of the list, so we can cross off that goal as well. Let's see how long we can stay there.

![afbeelding](https://user-images.githubusercontent.com/33519926/202716781-fd629600-c167-4038-9c7e-12cfae27d0a2.png)

**Comment by ocefpaf** [comment]
@Carreau is the mastermind behind closember. I'm pretty sure he has a "mission accomplished" feeling right now.

**Comment by Conengmo** [comment]
Thanks for organizing this @Carreau! It's much appreciated.

> If you don't mind once this is over I'd love to send you some questions and write a blog post on how you liked focusing on finishing things.

Sure thing, I'd be happy to help!

**Comment by Conengmo** [comment]
Only 7 unlabeled open issues remaining! https://github.com/python-visualization/folium/issues?q=is%3Aopen+is%3Aissue+no%3Alabel I'm confident we can resolve those before the month is over. We closed around 150 issues in the past few weeks :sweat_smile:

**Comment by Conengmo** [comment]
We got all unlabeled open issues! I'll tick off the goal to triage and label all open issues. Remaining open issues contain valid feature ideas/requests, still to be solved bugs and valid requests for better documentation in certain areas.

**Comment by Conengmo** [comment]
Looks like there is no more low hanging fruit left at the moment. I'll go ahead and compile a changelog for the upcoming release. It's going to be a big one!

**Comment by Conengmo** [comment]
I added the changelog for the upcoming release: https://github.com/python-visualization/folium/commit/2e0b4f69a4ec347ebe2a8f3c1ffab1ae259cc600. Looks like we are good to go! @ocefpaf could you bake a 0.14.0 release? I'll not merge new stuff until then.

**Comment by Conengmo** [comment]
It's still some hours for this last day of Closember, also depending on your timezone, but since I'm busy tomorrow I'm going to call it now already and say folium made the top of the closeboard:

![afbeelding](https://user-images.githubusercontent.com/33519926/204845581-1cb1aa05-e2d1-40a0-a8d1-6eafb7e7388e.png)

So I'll go ahead and mark that final goal as well :) Feels really good to have the project in a much better state now.

**Comment by ocefpaf** [comment]
I'm freezing this here for posterity:

![Screenshot from 2022-12-01 09-48-55](https://user-images.githubusercontent.com/950575/205057134-97c16a12-6944-432d-8600-40411989f92d.png)

**Comment by Conengmo** [comment]
> I'm freezing this here for posterity:

That looks great, thanks for sharing!
