### ISSUE TITLE
Provide option for in-line labelling

### ISSUE THREAD

**Issue by suryaya** [python-visualization/folium#1669]
Hello, thanks for this great python library.

**Is your feature request related to a problem? Please describe.**
A common use for web maps is to show line data such as contours or road lines. AFAIK this cannot be done easily with folium. For example, I have a set of contours in the geojson format to plot. I can use folium.GeoJson with a tooltip to get this result:

![image](https://user-images.githubusercontent.com/59785388/204413537-fee263b0-6f44-40af-bf37-45dfab3bb5c8.png)

However, there doesn't seem to be an easy way to show this ELEV value in-line without hovering. This would be a very useful feature when showing lien features such as creeks, contours, road lines etc. Something like this essentially:

![image](https://user-images.githubusercontent.com/59785388/204413694-c55b121b-ac44-4d87-b597-4262e4f7cdb2.png)

**Describe the solution you'd like**
Maybe a parameter in the `folium.Choropleth` or `folium.GeoJson` object that allows us to define in-line labels based on some field in the underlying dataset.

**Implementation**
folium is maintained by volunteers. Can you help make a PR if we want to implement this feature?

Unfortunately I have no idea how to implement that sort of feature. leaflet seems to have plugins that do this sort of thing:

https://stackoverflow.com/questions/42629909/contour-line-labels-on-leaflet-map

**Comment by suryaya** [comment]
Okay, I seem to have figured it out.

You can kind of get something like this by:

1. Converting the line-strings in the geojson into a `folium.PolyLine` object.
2. Using `folium.plugins.PolyLineTextPath` you can insert text along the polyline as a separate object. You can save the elevation data from the GeoJson and feed it into the text parameter

Result:
![image](https://user-images.githubusercontent.com/59785388/204425533-f6aec76e-1b32-4a97-90ec-ab9e7b90bd8d.png)

Still, would be cool to have it as a built-in parameter for a choropleth or geojson

**Comment by Conengmo** [comment]
Thanks for sharing your insights on this topic! I agree that using Polyline with PolyLineTextPath seems like a good way to do this. Note that the latter has parameters to customize the text placement and orientation.

As for a GeoJSON, it would be nice if tooltips could be opened permanently. Currently with GeoJsonTooltip I didn't get that to work correctly though. Not sure how that should be solved, and whether it's worth spending time on.

I'll close the issue since doing more custom work with GeoJson is not really within scope for folium. If somebody develops something further for this, please share it here though! We might adopt it in this repo. Otherwise, you might host it yourself and we can link to it.
