### ISSUE TITLE
Click twice to exit full screen

### ISSUE THREAD

**Issue by Winky678** [python-visualization/folium#1687]
**Describe the bug**
When I enter full screen mode, I need to click twice to exit full screen mode

**Comment by Conengmo** [comment]
Not something we're going to address in folium.

**Comment by afontenot** [comment]
I'm not sure why there's no interest in fixing this issue, because it presents as an obvious bug. Moreover, it's already been fixed in more recent versions of the upstream leaflet.fullscreen project, folium is just using a really old version.

Anyone who would like to fix this on their own can edit the folium plugin like so:

```patch
--- a/folium/plugins/fullscreen.py      2023-09-21 14:59:29.565815449 -0400
+++ b/folium/plugins/fullscreen.py      2023-09-21 14:58:55.985362484 -0400
@@ -40,13 +40,13 @@
     default_js = [
         (
             "Control.Fullscreen.js",
-            "https://cdnjs.cloudflare.com/ajax/libs/leaflet.fullscreen/1.4.2/Control.FullScreen.min.js",
+            "https://cdnjs.cloudflare.com/ajax/libs/leaflet.fullscreen/2.1.0/Control.FullScreen.min.js",
         )
     ]
     default_css = [
         (
             "Control.FullScreen.css",
-            "https://cdnjs.cloudflare.com/ajax/libs/leaflet.fullscreen/1.4.2/Control.FullScreen.min.css",
+            "https://cdnjs.cloudflare.com/ajax/libs/leaflet.fullscreen/2.1.0/Control.FullScreen.min.css",
         )
     ]

```

Note that I am deliberately using a non-current version of leaflet.fullscreen because of a CDN issue, which I have reported here: https://github.com/brunob/leaflet.fullscreen/issues/112

**Comment by Conengmo** [comment]
> I'm not sure why there's no interest in fixing this issue

because it’s not a bug in Folium, but in the upstream package. Note that the few maintainers we have are all volunteers doing this in their free time, I hope you can respect that. It’s too much work to dive into every issue ourselves.

> Moreover, it's already been fixed in more recent versions of the upstream leaflet.fullscreen project, folium is just using a really old version.

Good find! Would you like to open a PR with this change?

**Comment by afontenot** [comment]
> Note that the few maintainers we have are all volunteers doing this in their free time, I hope you can respect that.

No worries, I respect your time and volunteer effort, I'm definitely not saying you're obligated to fix this or any other issue. I read your original reply as a sign of disinterest in the problem, whereas you meant "we won't fix this *because* it's an issue with a different project, please report it to them instead."

> Good find! Would you like to open a PR with this change?

Will do, but note that I have an [open PR](https://github.com/cdnjs/packages/pull/1667) to fix an issue with cdnjs not distributing the image assets for the project. After that is merged, I'll file a PR here to use the latest version of leaflet.fullscreen.
