### ISSUE TITLE
How to organize groups in Layer Control

### ISSUE THREAD

**Issue by JohnyCarrot** [python-visualization/folium#1712]
Greetings,

I have a polygons which are part of sub groups (FeatureGroupSubGroup) and these sub groups are part of Groups (FeatureGroup).

What i need is "listing" it like on this image:
![grouping_folium](https://user-images.githubusercontent.com/107358703/214677066-129421d6-1478-4c01-b725-335a5b7fbbd6.png)
I need that my groups (shown as "Big group in image) will have sup groups shown like here and that i can either turn of / off whole group or turn off / on each sup group separatly even big groups are off for example. Currently, i have no idea how to do it.

Here is my code :

```python
    chranene_oblasti = folium.FeatureGroup("Chránené oblasti",control=False)
    druhy_stupen = folium.plugins.FeatureGroupSubGroup(chranene_oblasti,name="II. stupeň ochrany")
    treti_stupen = folium.plugins.FeatureGroupSubGroup(chranene_oblasti, name='III. stupeň ochrany')
    stvrty_stupen = folium.plugins.FeatureGroupSubGroup(chranene_oblasti, name="IV. stupeň ochrany")
    piaty_stupen = folium.plugins.FeatureGroupSubGroup(chranene_oblasti, name="V. stupeň ochrany")
    m.add_child(chranene_oblasti)
    m.add_child(druhy_stupen)
    m.add_child(treti_stupen)
    m.add_child(stvrty_stupen)
    m.add_child(piaty_stupen)

```
#### Problem description

Problem with this code is that it will just add Feature group (big group) as normal "object" in Layer control and it will either turn it off / on, as individual sub groups (which are not shown like on image above, but on the same level) cant be controlled then.

#### Expected Output
![grouping_folium](https://user-images.githubusercontent.com/107358703/214677066-129421d6-1478-4c01-b725-335a5b7fbbd6.png)

#### Output of ``folium.__version__``
'0.14.0'

**Comment by IndigoWizard** [comment]
@JohnyCarrot 
At the current moment there's no such way of having a sort of hierarchy display of layers on the layer panel. A recent addition to folium since [`version 0.14.0`](https://github.com/python-visualization/folium/releases/tag/v0.14.0) was the `GroupedLayerControl` #1592 which allows to spawn a separate layer panel (on top/bottom of the main panel) and can contain multiple layers under a group title (just text, no actual hierarchy group layer control).

Link to official folium documentaion notebook example: [GroupedLayerControl](https://nbviewer.org/github/chansooligans/folium/blob/plugins-groupedlayercontrol/examples/plugin-GroupedLayerControl.ipynb)

![image](https://user-images.githubusercontent.com/43890965/215000457-52965a18-b104-43b9-afda-cc11352053fb.png)

## Flaws
- It can't add raster layers to the groups (e.g: "gee" google earth engine layers) as far as I tried.
- If you want one "**main big group**" to control all sub groups it must be in the main layer panel  (do add_to(m) instead of the plugin).
- If you want **Main Sub Group** control of all layers in that subgroup, it needs to be the last one stacked in it's layer group (see image 2. **"All Group A"** / **"All Group B"** )
![image](https://user-images.githubusercontent.com/43890965/214999507-5cd48850-4b94-4394-868c-0b45ede8d5d8.png)

### NOTE:
The styling is not included in the plugin or folium. I done it to better illustrate and clarify the context.
You still can use [Branca](https://github.com/python-visualization/branca) + CSS to tweak the style if wanted.

**Comment by JohnyCarrot** [comment]
Thanks you so much...

This is it, even if i cant control sub groups, its not that big deal.

Love you

**Comment by zxdawn** [comment]
Ha, it would be nice to have big groups to turn on/off all subgroups inside and each subgroup can be controlled independently.
