### ISSUE TITLE
TagFilterButton doesn't work with MarkerCluster properly

### ISSUE THREAD

**Issue by karlk127001** [python-visualization/folium#1717]
`TagFilterButton` is a great new feature - thanks for that, but unfortunately it doesn't work well with `MarkerCluster`.
The problem is `TagFilterButton` filter only 'uncluster' (or in other words 'visible') markers, and markers that are inside cluster are not filtered. It causes that after increasing of zoom level (new markers become visible), some markers that don't match with filtering are visible.

There is simple example of code with this kind of situation:
```
import folium
from folium.plugins import TagFilterButton, MarkerCluster


m = folium.Map([40., 70.], zoom_start=5)
mc = MarkerCluster(name='all colors',).add_to(m)

for i in range(10):
    if i<5:
        folium.Marker([40+i, 74+i], tags=["red"], icon=folium.Icon(color='red')).add_to(mc)
    else:
        folium.Marker([40+i, 74+i], tags=["blue"], icon=folium.Icon(color='blue')).add_to(mc)

TagFilterButton(["red", "blue"]).add_to(m)
folium.LayerControl(collapsed=False).add_to(m)

m
```
After generating map with code above, you can try to filter to see only 'blue' and then increase zoom level - it shows core of issue.

I think that the best functionality for `TagFilterButton` will be filter also markers that are inside cluster. I didn't find way how to do it, so I decided to write about this. Maybe someone know if it is possible to change this functionality ?

**Comment by Conengmo** [comment]
I'm afraid I can't really help you with this. Often different plugins don't work well together. Since Folium is only a simple wrapper around these upstream Leaflet plugins, there's also not much we can do here. It would require somebody diving into the code of both those JS plugins to see if there's something that can be done. Since this is out of scope for Folium I'll close this issue. But if somebody finds out something about this please report back here!
