### ISSUE TITLE
Generating map to html takes ages. Can it be saved and then served ?

### ISSUE THREAD

**Issue by JohnyCarrot** [python-visualization/folium#1746]
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```python
m._repr_html_()

```
#### Problem description

Im adding a few ( about 5 000 polygons) and genereting map, more precisely ._repr_html_() is taking about 15seconds to end. Im just wondering, if there is any chance to speed this process or, if i can genereate html, and then, somehow, recreate it later to usable python class so can i work with it. Im planning to add a lot more polygons, and for me, waiting more than 5 seconds is no go. Im using it with django.

#### Expected Output
Work faster, please.
#### Output of ``folium.__version__``
0.14.0

**Comment by Conengmo** [comment]
Please check this page on how to use Folium with Flask, it will be similar for your use case with Django: https://python-visualization.github.io/folium/flask.html. I'd suggest caching the generated html.

If you need to regenerate the map on the fly, I'd suggest looking into doing that outside of the Django request-response.

Other than that there are currently no plans to work on Folium performance. Since Folium is maintained by volunteers, if somebody wants to look into that, they are welcome to!
