### ISSUE TITLE
Can popup trigger GroupedLayerControl ?

### ISSUE THREAD

**Issue by jamiechoi1995** [python-visualization/folium#1752]
I have multiple polyline in my map and some of them are highly overlapped,
I want to click one polyline that other polylines can disappear to make the target polyline more clear
I think GroupedLayerControl can do the similar thing but it seems that it cannot trigger by popup
Are there any solutions? thanks

**Comment by Conengmo** [comment]
I don't think there's a way in Folium currently to trigger showing/hiding elements by clicking on them. You would have to write some custom Javascript for that, using the Leaflet API.

It's a possible idea for a new feature for Folium, but since we're short on development capacity I'll not keep this open.

I suppose https://github.com/python-visualization/folium/issues/1751 should already help you with your issue of grouping and showing/hiding several polylines, so I'll close this one.
