### ISSUE TITLE
Being able to navigate through values in folium.Choropleth

### ISSUE THREAD

**Issue by BastienGauthier** [python-visualization/folium#1764]
**Is your feature request related to a problem? Please describe.**
When I need to plot a folium.Choropleth with several values over the same geometry, I need to reload the whole map, which can be quite long.

**Describe the solution you'd like**
I would like to have a way to update only the value (and the associated colors) of the Choropleth. I could use a fonction "update" such as :

``` 
m = folium.Map(...)
color_layer = folium.Choropleth(...)
m.add_child(color_layer, name = "colors_to_update")

m.update_child(data = new_data, name = "colors_to_update") # the new function
```

This would be very convenient for a temporal evolution over a country for exemple.

**Describe alternatives you've considered**
I did not find any alternative to reloading the whole map.

**Additional context**
Just to be noted that the need can be extended to Circle and CirleMakers color & radius for exemple.

**Implementation**
> folium is maintained by volunteers. Can you help make a PR if we want to implement this feature?

If an hint is given, maybe I can try, but I don't know Leaflet & js very well.
Maybe it is only a generalization of the TimeSliderChoropleth plugins ?

**Comment by Conengmo** [comment]
Maybe good to know that Folium is a one-way street from Python to Javascript. So  there's not really a way to 'update' a map from the Python side once the map has been generated.

Maybe I'm not understanding your question correctly, but couldn't this also be achieved by adding multiple choropleths to the map?

```
m = Map()
Choropleth(data_1, name="first data").add_to(m)
Choropleth(data_2, name="second data").add_to(m)
LayerControl.add_to(m)
```

**Comment by Conengmo** [comment]
Maybe you would benefit from using the `GeoJson` class directly instead of `Choropleth` and writing your own `style_function`. Maybe you can do something there. See https://nbviewer.org/github/python-visualization/folium/blob/main/examples/GeoJSON_and_choropleth.ipynb. But I guess you would also need some way of triggering the change in the JS side.

Otherwise you could maybe look into simplifying your geometry, so it loads faster.

I don't think we want to implement something to dynamically switch the choropleth data. If somebody does make something like that, I'd be happy to include a link to their repo in our documentation.
