### ISSUE TITLE
How to add popup to an image that is not a marker?

### ISSUE THREAD

**Issue by EmanuelCastanho** [python-visualization/folium#1785]
Hi,

I want to create an information button on the bottom-right of my page that, when clicked, pops up text information.

Currently, I am using this block of code, but I don't know how to add a pop-up:
```
# Add info
with open("configs/imgs/info-icon.png", 'rb') as img:
    b64_content = base64.b64encode(img.read()).decode('utf-8')
FloatImage('data:image/png;base64,{}'.format(b64_content), bottom=1, left=98, width="50px").add_to(map)
```

![Screenshot 2023-07-21 at 13 14 50](https://github.com/python-visualization/folium/assets/69935277/974e363d-1118-4efe-9f6e-80c6cf4dc317)

**Comment by IndigoWizard** [comment]
Hello @EmanuelCastanho 

You can alternatively use branca elements to render a div element on the map and inject your HTML/CSS/JavaScript for structure, layout and interactivity.

Here's an answer I gave on stackoverflow with **code example** that you can implement and customise with some JS to add the wanted effect instead of using float images. You can add Font Awesome icons, or link to local images without converting to base64, basic HTML;
[How can I add a text box to folium (with more or less the same behavior as the LayerControl panel)?](https://stackoverflow.com/questions/75493570/how-can-i-add-a-text-box-to-folium-with-more-or-less-the-same-behavior-as-the-l)

### preview:
![](https://www.pixenli.com/image/D2M7kEsT)

Hope you find it useful (don't hesitate to upvote if you like 👀 )

**Comment by IndigoWizard** [comment]
You're welcome @EmanuelCastanho
Also a bonus tip, since the bulk code is just HTML and CSS all in one block it can quickly fill up your main code, and if it's a big project it can be a pain to scroll down all that.
I suggest you structure your app as follows:
- Have a separate `mystyle.css` file
- Put your branca/html code in a separate file `app_ui.py`
- Import your style.css file within your `app_ui.py`
- Import your `app_ui.py` within your main code file `app.py`

This way, you won't have to re-excute your `app.py` everytime you try new changes to the CSS, you can just edit the `style.css` file instead and refresh your tab for the `index.html` file of the map and see the results (or open it in your VSCode live server as you would a web dev project).

### app_ui.py:

```python
info_button = """
{% macro html(this, kwargs) %}
<!-- YOUR HTML CODE GOES HERE-->
<head>
  <title></title>
  <link rel="stylesheet" href=""> // you can link your free font-awesome url here
  <link rel="stylesheet" href="src/mystyle.css"> // link your local css file here
</head>
<body>
  <div class="info-btn">
    <i class="fa-solid fa-circle-info"></i>
  </div>
</body>
{% endmacro %}
"""
```

### app.py:

```python
import folium
from branca.element import Template, MacroElement
import app_ui

# ... your main code here

# UI section
ui_element = ui.info_button
ui = MacroElement()
ui._template = Template(ui_element)

# adding your button/ui element to the map
m.get_root().add_child(ui)

```

**Comment by IndigoWizard** [comment]
You're welcome @EmanuelCastanho
Also a bonus tip, since the bulk code is just HTML and CSS all in one block it can quickly fill up your main code, and if it's a big project it can be a pain to scroll down all that.
I suggest you structure your app as follows:
- Have a separate `style.css` file at root or an src folder
- Put your branca/html code in a separate file `app_ui.py`
- Import your style.css file within your `app_ui.py` using `<link rel="stylesheet" href="src/style.css">`
- Import your `app_ui.py` within your main code file `app.py`
- Create a variable for your **ui_element** and assign to it the stored variable from `app_ui.py` as such: `app_ui.info_button`

This way, you won't have to re-excute your `app.py` everytime you try new changes to the CSS, you can just edit the `style.css` file instead and refresh your tab for the `index.html` file of the map and see the results (or open it in your VSCode live server as you would a web dev project).

### app_ui.py:

```python
info_button = """
{% macro html(this, kwargs) %}
<!-- YOUR HTML CODE GOES HERE-->
<head>
  <title></title>
  <link rel="stylesheet" href=""> // you can link your free font-awesome url here
  <link rel="stylesheet" href="src/style.css"> // link your local css file here
</head>
<body>
  <div class="info-btn">
    <i class="fa-solid fa-circle-info"></i>
  </div>
</body>
{% endmacro %}
"""
```

### app.py:

```python
import folium
from branca.element import Template, MacroElement
import app_ui

# ... your main code here

# UI section
ui_element = app_ui.info_button
ui = MacroElement()
ui._template = Template(ui_element)

# adding your button/ui element to the map
m.get_root().add_child(ui)

```

**Comment by Conengmo** [comment]
Thanks @IndigoWizard!
