### ISSUE TITLE
Is there a way to remove the 'Leaflet' part of a tile layer attribution?

### ISSUE THREAD

**Issue by araichev** [python-visualization/folium#1794]
Within Leaflet one can achieve this via `map.attributionControl.setPrefix('')` according to [this issue](https://github.com/Leaflet/Leaflet/pull/8109).
How to do this in Folium?

**Comment by Conengmo** [comment]
Yes, you need to add that Javascript snippet somehow, while using the map object name instead of `map`.

You can for example add the following to `Map._template`: `{{ this.get_name() }}.attributionControl.setPrefix('')`.

Or you can add a custom Javascript object to your `Map` object in Python. If you search around in the Github issues you should find some topics on that. You'll need the map object name again, for example:

```
m = folium.Map()
custom_js_snippet = f"{m.get_name()}.attributionControl.setPrefix('')"
```

Then add that custom JS snippet.

Hope that helps! I will close the issue, since we don't plan on adding this as an official option.
