### ISSUE TITLE
[Question] Does Folium support 3d terrain? 

### ISSUE THREAD

**Issue by GiuseppeGalilei** [python-visualization/folium#1840]
The main inspiration for this question are platforms like FatMap/Google Earth, I wonder if their functionality can be replicated using Folium.
I've searched a bit didn't find anything about Folium or even Leaflet supporting this.

Do you know if this is supported, or you have any idea if this can be implemented?
Thanks

**Comment by Conengmo** [comment]
If Leaflet doesn't support it, and it looks like it doesn't, then it seems far away to have this in Folium. Since Folium is a 'simple' wrapper of Leaflet and Leaflet plugins. We don't aim to extend Folium beyond that.

Probably best to look for other Javascript or Python libraries that have what you need.
