### ISSUE TITLE
Publish docs test fails due to missing fiona dependency

### ISSUE THREAD

**Issue by hansthen** [python-visualization/folium#2002]
**Describe the bug**
The automated tests are broken on main. There is an error in the publish docs test. 

**To Reproduce**
See this dependabot commit https://github.com/python-visualization/folium/commit/dc847327e02046befd87a3cee5f6b4e53e6866da.

**Additional context**
I tried to reproduce the issues locally. Locally, however, I do not have these errors. Perhaps someone can help write instructions on how to setup a sandboxed environment like in github to run these tests.

**Comment by prusswan** [comment]
For the fiona import error, I suspect it has to do with geopandas dropping fiona as a dependency (now replaced with pyogrio) since 1.0.0 (see https://github.com/geopandas/geopandas/blob/main/CHANGELOG.md#version-100-june-24-2024) - so it has to be imported if any of the workflow runs require it. Can't "prove" this as I could not find the logs for a previous successful run to compare against.

**Comment by Conengmo** [comment]
Fixed by https://github.com/python-visualization/folium/pull/2012
