### ISSUE TITLE
Proposal: Improve SideBySideLayers Plugin for Better Data Comparison

### ISSUE THREAD

**Issue by Mathieu-Ptz** [python-visualization/folium#2006]
I would like to propose an enhancement to the SideBySideLayers plugin, aiming to improve the comparison of datasets. Currently, the SideBySideLayers functionality in Folium does not fully support proper display and comparison of markers or other data-intensive visual elements. ie. I want to display different marker on each side.

In its current state, when using the SideBySideLayers plugin to compare datasets that include markers, they are not correctly separated across the layers. You can find a detailed description of this issue, including a minimal example and proposed solution, on my Stack Overflow post: [Stack Overflow: Folium SideBySideLayers markers not displaying correctly](https://stackoverflow.com/questions/79002102/folium-sidebysidelayers-markers-not-displaying-correctly-on-separate-layers/79085242#79085242).

![image](https://github.com/user-attachments/assets/50e23f6e-8276-4bb1-a5fd-2cdf09827dd8)

**Comment by hansthen** [comment]
I don't think we can help you. `Folium` is just a thin python wrapper around `leaflet` and its plugins. This seems to be behavior that is caused by the underlying plugin. 

The issue description and proposed change is very clear though. If you want this changed, you better transfer this issue with the maintainers of the leaflet side by side plugin:  `https://github.com/digidem/leaflet-side-by-side`. (You can do that using the `Transfer issue` icon on the right inside github.)

**Comment by Conengmo** [comment]
That's right, we wrap that plugin very lightly, so you'd have to look upstream.

@Mathieu-Ptz you might want to take a look at our DualMap plugin, which has a similar functionality but in some different ways. Here you see two maps next to each other, but both can have their own data. Only panning and zooming is synched. Hope that helps. https://python-visualization.github.io/folium/latest/user_guide/plugins/dual_map.html
