### ISSUE TITLE
Tweak the default width

### ISSUE THREAD

**Issue by ocefpaf** [python-visualization/folium#219]
I experiment master with jupyter yesterday and the default width is adding a left-right scroll bar.  We might need to tweak this a little bit.

**Comment by BibMartin** [comment]
You're true, I get the same thing. But it depends on the browser, resolution etc.

There's the same issue in mplleaflet and you can have a look at https://github.com/jwass/mplleaflet/pull/22 for ideas.

We can :
* Keep a fixed size and decrease it so that it will fit in most browsers
* Set the width to "100%" and use a fixed value for the height (600px seems reasonable to me).
* Use a trick inspired from http://fettblog.eu/blog/2013/06/16/preserving-aspect-ratio-for-embedded-iframes/ to set width to 100% and force a given aspect ratio (66% in this example).  

        iframe = '<iframe src="{html}" style="position:absolute;width: 100%;height: 100%;left: 0; top: 0;"></iframe>'\
            .format(\
                    html = "data:text/html;base64,"+base64.b64encode(html.encode('utf8')).decode('utf8'),
                   )            
        aspect_ratio_div = """
            <div style="position: relative; width: 100%;height: 0;padding-bottom: 66%;">{}</div>
            """.format(iframe)
        return aspect_ratio_div

**Comment by ocefpaf** [comment]
> Set the width to "100%" and use a fixed value for the height (600px seems reasonable to me).

Sounds good to me.

**Comment by andrewgiessel** [comment]
I kinda like the fixed proportion trick, but 100% x 600px is fine too.

ps: hi!

**Comment by ocefpaf** [comment]
Fixed in #221.

Thanks @BibMartin for the PR and @andrewgiessel for highlighting a better option than mine :wink:
