### ISSUE TITLE
Marker and other features are not accessible.

### ISSUE THREAD

**Issue by themiurgo** [python-visualization/folium#257]
Since 9abdd8f4d8ff5d106ff3f681c9150a039b9d7872 Marker, Popup and other features are not accessible from `folium.features`.

I believe what happened is that pep8 marked the imports as unused (as those classes are not used in `folium.features`), and tests did not catch that because they still involve the legacy usage (e.g. `Map.simple_marker` instead of `Map.add_to(Marker)`).

Two things we need to do to avoid this from happening again:
- We should decide where to access features from. I propose the root namespace).
- We should add / modify tests to use also the new feature addition.

**Comment by ocefpaf** [comment]
> I believe what happened is that pep8 marked the imports as unused

Not really.  I removed those on purpose as I thought they should not be on features.  But I am re-thinking my decision, since it is easier to access everything in there.

> We should decide where to access features from. I propose the root namespace

I like that idea.  We need to discuss this with @BibMartin and @andrewgiessel.

> We should add / modify tests to use also the new feature addition

Again... Our tests are our Achilles heels.  Let's leave this issue open until we implement something in that regard.

**Comment by ocefpaf** [comment]
> Again... Our tests are our Achilles heels. Let's leave this issue open until we implement something in that regard.

I am closing this and opening another issue.
