### ISSUE TITLE
Unable to assign string directly to popup using master branch

### ISSUE THREAD

**Issue by jelmelk** [python-visualization/folium#259]
Doing some small testing and I did the follwing:

    some_marker = folium.Marker(location=[45.5215, -122.6261], popup='test')

I would get this error: `AttributeError: 'str' object has no attribute 'get_name'`. If I change that to `popup=folium.Popup('test')` it works fine. Is that intended?

Main reason I'm asking is because it seems somewhat tedious having to call that to assign a string to the `popup`.

**Comment by BibMartin** [comment]
@jelmelk 
>  Is that intended?
> Main reason I'm asking is because it seems somewhat tedious having to call that to assign a string to the popup.

In the background, we cannot do without the `Popup` object, because one may be willing to create more complicated popups (with a vega chart for instance).

But I agree it's tedious, and in the foreground we can shortcut things in the `Marker` code to catch cases when the arg `popup` is a `str` (or `bytes`), and to replace it by `Popup(popup)`.

It'd be great if you did a PR for that (and thus join the <a href="https://github.com/python-visualization/folium/network/members">happy community of contributors</a>). Otherwise, I'll do it on Monday.

**Comment by jelmelk** [comment]
I'm looking at that right now. Would it be better to change each marker individually since the error rises at `map.py` on line 389 for `Marker` and `element.py` on line 414 for `CircleMarker` etc...

They all have `element.py` line 46 in common which is where the exception is actually being called from. What would be the preference in this case?

**Comment by BibMartin** [comment]
I imagine you can simply fix it in the `Marker.__init__` is testing when `isinstance(popup,text_type) or isinstance(popup,str_type)` and then overwrite the popup attribute.

**Comment by themiurgo** [comment]
We should strive to generalise this, while we're at it. You might want to have a popup also for Polylines, for example.

**Comment by BibMartin** [comment]
Fixed by #283. Closing this.
