### ISSUE TITLE
geo_json with pandas series problem

### ISSUE THREAD

**Issue by gbenegas** [python-visualization/folium#31]
If i do:
```
map.geo_json(geo_path=geo_json, data=series, key_on='feature.id')
```
I don't need to pass the columns argument, as it is a series. However, columns, initialized as None, is used in the function.
```
/home/gonzalo/anaconda/lib/python2.7/site-packages/folium/folium.pyc in geo_json(self, geo_path, geo_str, data_out, data, columns, key_on, threshold_scale, fill_color, fill_opacity, line_color, line_weight, line_opacity, legend_name, topojson, reset)
    621 
    622             #D3 Color scale
--> 623             series = data[columns[1]]
    624             domain = threshold_scale or utilities.split_six(series=series)
    625             if len(domain) > 6:

TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by ocefpaf** [comment]
@gbenegas  It is not possible because folium expects a one-to-one mapping with the GeoJSON.  See the notebook below:

http://nbviewer.ipython.org/urls/gist.githubusercontent.com/ocefpaf/77e20befcf9018c32fa1/raw/e0db1f9e34e535e97b815803510957b06f8bf5ed/test_choropleth.ipynb

(Sorry it took to long to answer.)
