### ISSUE TITLE
GeoJSON / choropleth popups

### ISSUE THREAD

**Issue by baobobs** [python-visualization/folium#311]
Just to be clear, popups for GeoJSON / choropleth layers are not currently supported, correct? Is there a time frame as to when this may be implemented?

**Comment by ocefpaf** [comment]
Hi @baobobs,

You can add popups on GeoJSON in a very flexible way using [latest master](http://nbviewer.ipython.org/github/python-visualization/folium/blob/master/examples/Popups.ipynb).  Note also that [`onEachFeature`](http://nbviewer.ipython.org/github/ocefpaf/folium_notebooks/blob/618e31754aa9325cae6c315b687bea95f3f92ae4/test_geojson_popup.ipynb) is present since [`v0.1.5`](https://github.com/python-visualization/folium/pull/102/files).

> Is there a time frame as to when this may be implemented?

We do not have time frames for anything.  Folium is maintained by volunteers on their spare time.

(We can be persuaded to move faster when we receive some love: like PRs :wink:)
