### ISSUE TITLE
Use folium offline

### ISSUE THREAD

**Issue by ispmarin** [python-visualization/folium#351]
I'm planning on using folium to plot a few maps but noticed that everytime I replot something folium goes  back to the internet and fetch the map data. Is there a way to configure it to download all map data and use it offline?

**Comment by ocefpaf** [comment]
Not really.  The whole goal of folium is to leverage the base map using a Web Tile Service (WTS). (And in some cases even more than just the base map is downloaded.)

Maybe someone could implemente a cache system to save a certain area/zoom level, like phones do, to work offline.  A PRs with such functionality would be welcomed :wink:

**Comment by ocefpaf** [comment]
BTW, if you your goal is to produce static figures, take a look at [cartopy](http://scitools.org.uk/cartopy/).

**Comment by ispmarin** [comment]
Thanks @ocefpaf. I'm doing an [evaluation](https://github.com/ispmarin/maps) of the mapping options ATM for Python and being interactive is one of my requisites. I'm looking at cartopy but so far there are several problems installing it.

**Comment by ocefpaf** [comment]
>  I'm looking at cartopy but so far there are several problems installing it.

Do you use [`conda`](http://conda.pydata.org/docs/)? If so try:

`conda install -c ioos cartopy`

**Comment by ispmarin** [comment]
Nope, using standard pip, and it seems that [the problem](https://github.com/SciTools/cartopy/issues/726) is something with the underlying libraries. It installs fine.

**Comment by linwoodc3** [comment]
Is this a feature that's coming or has it been dropped?

**Comment by ocefpaf** [comment]
> Is this a feature that's coming or has it been dropped?

Folium is a leaflet wrapper. Leaflet render map tiles from a server. Unless you set a local server for your tiles there is no way to display slippy maps without an internet connection and a map server.

**Comment by linwoodc3** [comment]
There is a way to "hack" folium to work offline.  I used what's described below and was able to get `folium.Map()` working and rendering a geojson of a country without being online.

How to do it:
*  You will need to change the `_default_css` and `_default_jss` links (lines 225-257) to hit something stored on you local network.  The lines are in the `element.py` file. You'll need to run a few steps

    *  Download copies of all the files found in lines `225-257` of `element.py`
        *  For example, here is [the js markercluster](https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/0.4.0/leaflet.markercluster.js)
        *  You would simply save this file to your local computer (or get it on your network) and accessible

    *  Then, change the links in `element.py` to point to your local copy of these files.


**Warning**  If you make changes to `element.py`, make sure to save a copy of `element.py` somewhere else because if you update `folium`, your changes get overwritten.

**Comment by celebrimborOOO** [comment]
Hello, would there be any way to use it offline?

**Comment by linwoodc3** [comment]
@celebrimborOOO , I gave some instructions which worked for me above.

**Comment by morteza3000** [comment]
@linwoodc3 can you tell me where can I find element.py file?
I can't find it in below folder!
"C:\ProgramData\Anaconda2\Lib\site-packages\folium"

**Comment by linwoodc3** [comment]
@morteza3000 , I haven't tested this fix with the new files, but here is what you can try.  You would now change `folium.py`:

`folium.py`.  The lines you'll need to change are: https://github.com/python-visualization/folium/blob/f8a12a64db15a5f4b44058f52c436a741fdfdd13/folium/folium.py#L28-L52

You can find the location of your file by doing this:

1.  First, install folium
```bash
pip install folium
```

2.  Then find where folium is installed so you can access the file
```python
import folium
import os

# see if the folium.py file is there
print(os.listdir("/".join((folium.__file__).split('/')[:-1])))

# get the path; copy this or navigate to location
print("/".join((folium.__file__).split('/')[:-1]))
```

Copy the output of the last print statement to navigate to that file. Now just change the `_default_js` and/or _default_css

**Comment by morteza3000** [comment]
@linwoodc3 Thanks a lot, it works for me. is there any way to have base map (tiles) offline too?

**Comment by and-viceversa** [comment]
For those like me who found this much later...

[Here's](https://github.com/and-viceversa/folium_offline) a quick Folium extension that supports offline raster tile schemes in .mbtiles and standard {z}{x}{y} format. Offline means you rolled your own raster tiles.

I've been using [TileMill](https://github.com/tilemill-project/tilemill) to roll my own tiles.

@linwoodc3 's method works, but it's generally not advised to hack on your dependency code.

Instead this just overrides `raster_layers.TileLayer._template`, `folium._default_js`, and `folium._default_css` to point locally instead of the Leaflet CDNs.

Simple Usage:
Grab folium_offline.py
Change variables in main() to suit your needs
Add Folium code to make maps

**Comment by giagia96** [comment]
Hi all!
Did anyone tried to do this in Dash? The html generated by and-viceversa script works, but when I put it in an html.IFrame it doesn't show the map, just the marker that I put on it.

**Comment by and-viceversa** [comment]
I'm having this issue too, but without IFrames. For some reason {z}{x}{y} works just fine offline, while .mbtiles only works offline in Edge.

**Comment by Waffleboy** [comment]
@and-viceversa hey man, I'm using your script with generated tiles using tilemill but im getting 

```
Leaflet.TileLayer.MBTiles.js:22 Fetch API cannot load file:///storage/git/folium_offline/data/tiles/your_tiles.mbtiles. URL scheme must be "http" or "https" for CORS request.
```
When I load index.html and its completely grey.

Any idea on this?

**Comment by YoungGer** [comment]
@Waffleboy  I ran into a similar problem. I downloaded .mbtiles files. However, I get the error
![image](https://user-images.githubusercontent.com/7279683/103750449-b8769a00-4ffe-11eb-8291-e08d8dd7ea47.png)

Can you give me some suggestions how to solve this problem? I don't understand how to get tilesets from mbtiles files.
Also, @and-viceversa Could you give me some advice, too? 
Thanks a lot.

**Comment by and-viceversa** [comment]
I spent a fair ammount of time trying to do this mid last year. The idea was to build offline base maps with OSM in .mbtiles raster format using TileMill. Then you simply create your Leaflet/Folium overlay and you have full offline capability.

However, there is a browser security issue. In 2019, modern web browsers [restricted](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp) access to urls that originate from `file://` due to potential security vulnerabilities. At the time I was working on this, certain versions of Microsoft Edge had not patched the vulnerability - so you could still use the technique. As of right now I don't know anyway around reading .mbtiles from disk other than spinning up a local HTTP server to serve the tiles to the browser.

**Comment by gg-bt** [comment]
@and-viceversa , first of all thanks for your the work done.
I have a question for you, I want to use the folium offline but I don't want to put the map in a browser. I am developing a standalone GUI. The map is placed in a QtWebEngine object and displayed in the GUI. I need to keep the capability to zoom in and out as well as moving around the whole globe. Is this something achievable with your implementation? Sorry for the ignorance, what would be the best solution... mbtiles or using the .png?
Thanks a lot in advance for the support

**Comment by and-viceversa** [comment]
@gg-bt I'm not quite sure what you're asking. The `folium-offline` script was a one off demonstration for offline tile use. I've never used QtWebEngine so I can't help there.

First, you need to generate some tiles. 

[TileMill](https://github.com/tilemill-project/tilemill) is the tried and true software to build your own *raster* tiles. The output tiles are stored in either a file structure as individual images (png/jpg), or packaged together in a single .mbtiles file (which is actually just an sqlite db). [QGIS](https://www.qgis.org) can also be used to generate raster tiles. The .mbtiles file is almost always preferable for offline use because it is much more portable. The file structure method will generate millions of images depending on your area size and zoom level.

These days, *vector* tiles are the new technology. The common open source software is [OpenMapTiles](https://openmaptiles.org/). I haven't tried vector tiles offline with `folium` due to the browser security restriction listed above, because my requirement was to run in the browser. If I remember correctly, you can still use the file structure method offline to avoid the security issue but it is unwieldy.
