### ISSUE TITLE
embed map workaround

### ISSUE THREAD

**Issue by montrealks** [python-visualization/folium#394]
All of the guides I have read for getting Folium embedded into an iframe aren't working. I think maybe it was updated but not included into the documentation?

Typically the instruction looks like this:
    `def inline(m, width, height):`
        `"""Returns an embedded iframe of a folium.map."""`
  `  m._build_map()`
    `src = m.HTML.replace('"', '&quot;')`
    `style = "width: {}px; height: {}px".format(width, height)`
    `return '<iframe srcdoc="{}" style="{}"; border: none"></iframe>'.format(src, style)`

HTML(inline(map, 900, 500))`

where 'm' is an instance of 'folium.Map'

I have tried using this code to generate the code for embedding. But it always returns an error: `AttributeError: 'Map' object has no attribute '_build_map'`

**Comment by ocefpaf** [comment]
If you are using the latest version, and if you are talking about embedding the map in the notebooks,  that should not be necessary. Just leave the `m` object as the last line of your notebook cell.

**Comment by montrealks** [comment]
I am talking about embedding the map into a webpage. Not really sure what notebooks is.

**Comment by crashish** [comment]
@ocefpaf is more interested in closing issues than actually answering questions it seems

**Comment by joshuacano** [comment]
I think he may just actually be busy with other responsibilities, is there something I or another contributor can help you with?
Joshua Cano

**Comment by ocefpaf** [comment]
> @ocefpaf is more interested in closing issues than actually answering questions it seems

folium is maintained by volunteers at their spare time without any personal profit. So no core dev concern is to close instead of answering.

> @ocefpaf I am talking about embedding the map into a webpage. Not really sure what notebooks is.

The `inline` function you mentioned above was created with the notebook in mind. To embed in a webpage you can save the `HTML` and work with pure text from there. That means you can skip the lines

`m._build_map()` and `src = m.HTML.replace('"', '&quot;')` from your script and substitute them with `open` and `readlines()`.
