### ISSUE TITLE
Map rotation?

### ISSUE THREAD

**Issue by wfbradley** [python-visualization/folium#426]
Is it possible to specify a map rotation to get something like, e.g., [this](http://openlayers.org/en/v3.1.0/examples/rotation.html)?

If not, may I request this as a future feature?

**Comment by ocefpaf** [comment]
Interesting. We do not support that, but PRs are welcomed :wink:

**Comment by ocefpaf** [comment]
According to https://stackoverflow.com/questions/35060889/how-to-rotate-leaflet-js-map leaflet does not support rotation.

We could add an `openlayers` hack example, like the 3D globe, but that won't be a native `folium` class because we cannot guarantee that all the leaflet functionalities would work.
