### ISSUE TITLE
All Base maps loading at the same time

### ISSUE THREAD

**Issue by antiquechrono** [python-visualization/folium#483]
I'm not sure If this is a bug in Leaflet or Folium, but if you add a bunch of tile layers and use a layer control it will cause every tile layer to be active at the same time and download tiles for every layer. As soon as you select a new layer it starts loading tiles from only that layer like it should.

``` Python
import folium

m = folium.Map(location=[44, -73], zoom_start=3, tiles=None)
folium.TileLayer('openstreetmap').add_to(m)
folium.TileLayer('stamentoner').add_to(m)
folium.TileLayer('stamenTerrain').add_to(m)
folium.TileLayer('stamenwatercolor').add_to(m)
folium.TileLayer('cartodbpositron').add_to(m)
folium.TileLayer('cartodbdark_matter').add_to(m)
folium.LayerControl().add_to(m)

m.save('map.html')
```

**Comment by ocefpaf** [comment]
> I'm not sure If this is a bug in Leaflet or Folium,

I am pretty sure it is `folium`. I even reported this myself somewhere but I guess I closed it. I will look into it as soon as possible.

**Comment by Conengmo** [comment]
This bug has been fixed already. Tile layers are by default not overlays, so only one of them is activated at a time. Only that one is loaded by the browser. If multiple tile layers are passed the `overlay=True` argument, they are loaded at the same time. Unless you untoggle them on map load with `show=False`.

I'm closing this issue since it is not an issue any more.
