### ISSUE TITLE
Feature request: Option to handle missing keys in choropleth()

### ISSUE THREAD

**Issue by Khris777** [python-visualization/folium#526]
Lets say I want to fill a full world map with data. I'm using a geo json with the full world map data including iso country codes.

Now I have my data which consists of a pandas dataframe with iso country codes and numbers. However not every country code in the world map data is also in my data.

Doing this

    wMap.choropleth(geo_path=geoFile,data=df,key_on='feature.properties.iso_a3',columns=['Country','numbers'],...)

then leads to a `key error`.

To solve this I have to read out all country codes in the world map data and add the missing ones with zero values into my dataframe so that every key in the world map data is explicitely supplied with a value.

It would be great if there was an option to handle missing keys more gracefully so that you just need to provide a missing value that is inserted when a key is not present in the data.

**Comment by ocefpaf** [comment]
@Khris777 it seems that the pre-processing to use the current implementation is not too bad and, assuming something for the missing key, would lead to changes in the `docs`, discussion on what should be the default, etc.

If you want to send a PR I will gladly review it but that is not something I want to leave it here hanging as a feature request since I am +0.45 to supporting this.
