### ISSUE TITLE
Crossing the dateline causes a polygon display wrap issue

### ISSUE THREAD

**Issue by wckoeppen** [python-visualization/folium#55]
I'm using folium to display some polygons that cross the international date line, but the polygons get wrapped to the far right side of the map.
![screen_20](https://cloud.githubusercontent.com/assets/5704500/5136153/a597dcb0-70cf-11e4-9e50-70359a47450b.jpeg)

**Comment by wckoeppen** [comment]
@birdage whoops! sorry, somehow I missed seeing this. Here's the ipython notebook:
https://github.com/wckoeppen/bering-seabird-vulnerability/blob/master/bin/Bering%20Seabirds.ipynb

The geogson is in the second cell.

(But don't judge me on my terrible loops and other bad coding practices, I'm new.)

**Comment by birdage** [comment]
@wckoeppen ALL THE JUDGEMENT! (kidding, ill take a look)

**Comment by ocefpaf** [comment]
> I'm honestly not sure how to address this- seems like a GeoJSON or TopoJSON polygon issue?

After reading a lot about the GeoJSON format specs I found out that the recommend way around this issue is to break the -180, 180. Here is an example:

http://nbviewer.ipython.org/gist/ocefpaf/f03e2cb878c891716518

I am closing since we don't have any plans to try to be smart about this issue and do that automatically.

**Comment by ocefpaf** [comment]
If anyone finds this issue take a look at:

https://github.com/Leaflet/Leaflet/pull/1293
