### ISSUE TITLE
 'module' object has no attribute '__version__'

### ISSUE THREAD

**Issue by WMLek** [python-visualization/folium#603]
Hi. I am new to folium and would like to run it on local machine Python27.  I tried to run the following codes

import os
import folium
print(folium.__version__)

but encountered the following error message

Traceback (most recent call last):
  File "C:\Python27\folium_map.py", line 9, in <module>
    print(folium.__version__)
AttributeError: 'module' object has no attribute '__version__'

Hope someone can advice.

**Comment by ocefpaf** [comment]
You have it correctly in the title. It is '__version__', not version.

**Comment by WMLek** [comment]
Many thanks.  I tried again

import os
import folium
print(folium.__version__)

but still encountered the following error message

Traceback (most recent call last):
File "C:\Python27\folium_map.py", line 9, in
print(folium.__version__)
AttributeError: 'module' object has no attribute '__version__'

I also tried

import os
import folium
mapa = folium.Map(location=[45.5236, -122.6750])

but still encountered the following error message

  File "C:\Python27\folium_map.py", line 10, in <module>
    mapa = folium.Map(location=[45.5236, -122.6750])
AttributeError: 'module' object has no attribute 'Map'

I think I am missing something fundamental. Look forward to your guidance.

I seem to be able to execute these codes on Juypter Notebook, but not on the local Python27.

**Comment by joshuacano** [comment]
You need to take a look at your local Python27 and ensure it is loaded. Ipython uses a separate install of Python normally called conda or Anaconda. You are going to want to make sure that you are using the version of python that conda uses, when trying to import the map (Generally in %PATH%/anaconda/bin/python)

if you want to install this to your system-wide Python environment you can use pip install folium, and then you will have this package loaded. I suggest you start by looking into conda installs and pip installs. If you'd like to learn more I'd suggest you learn about the virtual environment, allowing you to control a custom environment with particular packages installed.  

Otherwise, Ipython is a great place to use folium. Thats another option for you.

Also as a brief aside, to view what packages you have installed you can run the command: pip list.
This will show you what packages are installed. 

Hope this helps!

**Comment by ocefpaf** [comment]
There is something broken with your installation like @joshuacano said. (It looks like you are on Windows so some details on how you installed `folium` would help us debug this.)

BTW, this should work (all from the command prompt):

```shell
pip install folium
python -c 'import folium; print(folium.__version__)'
0.3.0
```

If that works then your installation is OK and your Jupyter instance is the one calling something different.
