### ISSUE TITLE
Value Check on Location parameter of the Map creator

### ISSUE THREAD

**Issue by radumas** [python-visualization/folium#625]
I accidentally tried calling `folium.Map([45.0 -79.0])` in a Notebook, and it failed silently leading me to tried to decode the indecipherable JS console output.

There could be a simple check to see, if `location` is a list, that it has 2 and only 2 values.

**Comment by ocefpaf** [comment]
That is doable. Do you want to try a PR?

On May 26, 2017 4:40 PM, "Raphael Dumas" <notifications@github.com> wrote:

I accidentally tried calling folium.Map([45.0 -79.0]) in a Notebook, and it
failed silently leading me to tried to decode the indecipherable JS console
output.

There could be a simple check to see, if location is a list, that it has 2
and only 2 values.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/python-visualization/folium/issues/625>, or mute the
thread

**Comment by radumas** [comment]
I'd be happy to!

**Comment by ocefpaf** [comment]
Nice. Ping me if you need any help.

**Comment by radumas** [comment]
I've written up the code. Just wondering how to write tests compatible with your current testing framework, I'm only familiar with using the built-in `unittest` library.

**Comment by ocefpaf** [comment]
Start a PR and I can help you with the tests. I'm traveling at moment though and it may take a while for me to look at it.

**Comment by radumas** [comment]
Just started that. Thanks!

**Comment by ocefpaf** [comment]
Fixed in #626
