### ISSUE TITLE
Get information about Clicked object

### ISSUE THREAD

**Issue by toknowjoyman** [python-visualization/folium#773]
I'm using a PyQt QWebEngineView to display the folium generated html. And I need to know the name/id/path of a polyline when a user clicks on it.  
What would be the best way to go about getting this, or any information, about an such an event on the map back to folium for evaluation?

**Comment by Conengmo** [comment]
I don't know a solution, but maybe I can contribute some thoughts.
As far as i know Folium renders a html file and that's that. Some stuff can be clickable, but then that is part of the 'static' page, and doesn't get back to Python. To get some variable back into your script you would need something else. I'm not familiar with PyQt's QWebEngineView, but maybe there is something there to catch click events on the page? You could also use something like Flask, though at that point I'm not sure if it makes sense to keep using Folium instead of going with Leaflet directly.

**Comment by ocefpaf** [comment]
> As far as i know Folium renders a html file and that's that.

Yep. In the past we flirted with the idea of doing something [like this](http://jakevdp.github.io/blog/2013/06/01/ipython-notebook-javascript-python-communication/), but that is no longer "allowed" due to notebook security reasons and only `ipyleaflet` can provide bi-directional communication. Also, I have no idea how to do that with `Qt` :grimacing: 

With that said I am not saying it is impossible, just not easy and out of the scope of `folium`. Closing this.
