### ISSUE TITLE
native zoom option on tiles missing?

### ISSUE THREAD

**Issue by AndrewAnnex** [python-visualization/folium#789]
```python
opm_attr='<a href="https://github.com/openplanetary/opm/wiki/OPM-Basemaps" target="blank">OpenPlanetaryMap</a>'

m = folium.Map(attr=f'NASA/MOLA |{opm_attr}', max_zoom=5, 
           tiles='https://s3-eu-west-1.amazonaws.com/whereonmars.cartodb.net/mola-color/{z}/{x}/{-y}.png')

m

```
#### Problem description

I want to be able to set the native zoom option in leaflet for a tile layer but I don't see a way to do it. I currently set the max zoom but If I disable it and zoom in the tiles are not interpolated and I am left with gray tiles.

#### Expected Output

I would expect to be able to zoom in past whatever native limit there is to a tile, sure it would be interpolated but that is ok for some uses.

#### Output of ``folium.__version__``
'0.5.0'

**Comment by Conengmo** [comment]
I reproduced your problem and may have found what causes it. (Pretty cool map by the way!)

If I get to zoom level 7, the tileserver responds with HTTP status 403 Forbidden for each tile. So Leaflet expects to receive tiles, is unable to get them, and then displays grey tiles. 

The same happens if you use OpenStreetMaps and go past zoom level 18 or 19 (I think), you get a HTTP status 404 Not Found on each tile.

A solution is to provide a `maxNativeZoom` option to the `tileLayer` function. It tells Leaflet to not retrieve tiles for zoom levels beyond this value. This is not implemented in Folium, so you will have to do it in the javascript that is created by Folium. For example:
```
var tile_layer_1234 = L.tileLayer(
                'https://s3-eu-west-1.amazonaws.com/whereonmars.cartodb.net/mola-color/{z}/{x}/{-y}.png',
                {
  "attribution": "NASA/MOLA |<a href=\"https://github.com/openplanetary/opm/wiki/OPM-Basemaps\" target=\"blank\">OpenPlanetaryMap</a>",
  "maxNativeZoom": 6,
  "maxZoom": 18,
} ).addTo(map_1234);
```

**Comment by AndrewAnnex** [comment]
It seems that would be the solution, additionally one could expose additional options like this via a kwargs parameter for greater flexibility.

**Comment by ocefpaf** [comment]
> I reproduced your problem, pretty cool map!

Indeed. I could not resist BTW: http://nbviewer.jupyter.org/gist/ocefpaf/9f82d23604200ea2324a56dd99ba9f03

>  This is not implemented in Folium, so you will have to do it in the javascript that is created by Folium. 

Yep. But it seems that you are already on it. Thanks @Conengmo!

**Comment by AndrewAnnex** [comment]
@ocefpaf I haven't had time to test, but it looks like this has been fixed.
