### ISSUE TITLE
Folium Heatmap with time only shows a map with NO time play control buttons or heat

### ISSUE THREAD

**Issue by sharlynx** [python-visualization/folium#852]
Hi, I tried the example code from folium for the heatmap with time in my macbook, and it works fine.

But when I work on a windows, while it works out for the static heatmap; for the heatmap with time, it only shows a map, without any heat or buttons to play. Since the windows computer is from work. I am not sure if I need to change anything for the browser or anything else.

FYI, for the windows I installed the conda python 3.6 and this folium - pip install git+https://github.com/python-visualization/folium

Thanks a lot!

**Comment by Conengmo** [comment]
You're right, the heatmap with time is not working, not even in [the example](https://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/HeatMapWithTime.ipynb). In the console I get an error:

`Loading failed for the <script> with source “https://cdnjs.cloudflare.com/ajax/libs/heatmap.js/2.0.2/heatmap.min.js”.`

So turns out uBlock Origin is blocking loading the heatmap javascript. Can you try disabling your adblocker, see it that helps?
