### ISSUE TITLE
TimestampedGeoJson / Refresh for each time ? 

### ISSUE THREAD

**Issue by zefno** [python-visualization/folium#889]
Hello !

I'm using TimestampedGeoJson for drawing MultiPolygon and I would like to know if it's possible to only display the MultiPolygons associeted with the timestamp indicated on the slider and not the previous ones in addition. 

Thanks

**Comment by Conengmo** [comment]
Yes that's possible. You can use the `duration` argument to make sure only the most recent point is displayed. 

You can see in the second example of `TimestampedGeoJson` in the plugins notebook (https://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/Plugins.ipynb) that the green circles disappear after each step. That's because of the `duration` argument.
