### ISSUE TITLE
How to make heatmap weights not be influenced by the number of points in a region?

### ISSUE THREAD

**Issue by rodrigosnader** [python-visualization/folium#902]
#### Problem description

I'm trying to build a home value Heat Map for a city. My Dataframe contains Latitude, Longitude, and Price (variable which is suppose to behave as weight). Cheap areas should be green and expensive areas, red. The problem is that some poor regions with many dots seem to be much more expensive than really expensive areas with a few dots, because those dots overlay each other and turn that region red. How to overcome this problem?

**Comment by Conengmo** [comment]
I think that a heatmap is not a suitable thing for your use case. It is meant to show at which places many points are. So the problem that you're having (dots overlapping make the region red) is the basic functionality of a heatmap.

I guess you want to make a choropleth. This is implemented in folium, though you would need to preprocess your data to make regions. 

Another idea is to maybe make multiple heatmaps. Suppose you split your values in low and high. Then make a heatmap showing where the low values cluster, and one where the high values cluster.  Maybe if you use different colors and make both layers transparent it gives a decent image? I haven't tried this.

Hope that helps a bit! I'd be interested to know what solution you'll find for this.

**Comment by rodrigosnader** [comment]
@Conengmo I think that choropleths are not the thing I'm looking for, since "a choropleth map shows a change across a geographic landscape within enumeration units such as countries, states, or watersheds(...)", and what I'm looking for is a continuous color change based on house prices. A heatmap with 'weights' sounds to me as exactly that, what else would be the purpose of having weights? Doesn't it look like there should be a way to specify what makes an area hotter or colder?

Thank's for the ideas!

**Comment by Conengmo** [comment]
You're right about the hold and cold analogy. Each point you add to a heatmap adds a certain heat. More points => more heat. The weight you give each point is the amount of heat. So even if points have a low weight, they still add heat. So if you use housing price as a weight, every point will add heat.

You're looking for something that averages the values of overlapping points. A heatmap doesn't make averages, but instead sums the values of overlapping points.

If you search for 'housing price heatmap' you will find most images are chloropleths:
https://www.google.com/search?q=housing+price+heatmap&tbm=isch

There is one example of a heatmap, but there they don't use the housing price as a weight, but the difference between asking price and amount paid. That leads to positive and negative numbers.
https://www.canadianbusiness.com/blogs-and-comment/check-out-this-heat-map-of-toronto-real-estate-prices/

So one solution is to create regions, calculate the average asking price per region and create a chloropleth.

Another is to transform your data into positive and negative weights. But keep in mind that more points => more heat.

I just came across this repo that seems to do exactly what you're trying to do, so that could also maybe solve it:
https://github.com/jeffkaufman/apartment_prices

**Comment by brianxu7985** [comment]
Is that possible to calculate the weight basing on price? For example, area A price is $1000, area B price is $2000, you may add 2 points at area B, to reflect the 2x times "hot" than area A. I believe this could be done by pandas dataframe. Does that make sense?

**Comment by Conengmo** [comment]
I'm closing old issues that are not actionable. Feel free to add new information, we can reopen if needed.

**Comment by jackyangara** [comment]
I think one way to do it is by normalizing everything. First, group the price by area/region and aggregate by it's mean. This way you can see which area/region is poor or rich. Then you normalize the price with 100 as the limit. e.g. if the price ranges from $2.5 to $30, $30 becomes 100, and calculate the rest.

Then add multiple points depending on the normalized price. For area with 100 for it's "normalized price", add 99 points to that exact spot. This way, you can have red color here. For area with $2.5 or 1 "normalize price", do not add any points, so the color will stay blue.
