### ISSUE TITLE
Update MapBox to v4 ?

### ISSUE THREAD

**Issue by moccand** [python-visualization/folium#922]
calls to MapBox basemaps use MapBox API V3 (examples from jupyter notebook)

```python
map_mapbox = folium.Map(
    location=[48.853, 2.35], 
    zoom_start=16, 
    tiles='Mapbox',
    API_key='mytoken',
    attr=attr)

map_mapbox

```
gives wrong call to basemaps from MapBox API V3

http://b.tiles.mapbox.com/v3/mytoken/18/132783/90184.png => HTTP 400 Bad Request

using manual configuration with  MapBox API V4 

```python
map_mapbox_custo = folium.Map(
    location=[48.853, 2.35], 
    zoom_start=19, 
    tiles='https://api.mapbox.com/v4/mapbox.streets/{z}/{x}/{y}.png?access_token=mytoken',
    attr=attr)
map_mapbox_custo
```
gives good results.

**Comment by Conengmo** [comment]
Thanks for pointing this out. Our current string format for Mapbox is:
`http://{s}.tiles.mapbox.com/v3/{{ API_key }}/{z}/{x}/{y}.png`

* Is v3 deprecated and can we safely switch to v4? Or do we need to provide the option to choose a version?
* Is the url format changed in v4?

**Comment by moccand** [comment]
User with old tocken still can use v3 but new users (since 2015) can only use v4. 

If most of geopy users use free tocken i don’t think keeping v3 compatibility is a « Must have ».

On mapbox documentation there is a list of basemaps :

https://www.mapbox.com/api-documentation/#retrieve-tiles

So same system based on two words and arleady available for other basemap providers un geopy can be used.

**Comment by virgoaugustine** [comment]
Probably late to the party but for users like @Conengmo having issues with Mapbox tiles(mostly a 401 unauthorized error), this is what worked for me.
 #Instead of passing for example `tiles="Mapbox Bright"` to your `folium.Map()`, you would pass `tiles="https://{s}.tiles.mapbox.com/v4/mapbox.world-bright/{z}/{x}/{y}.png?access_token={DEFAULT_PUBLIC_ACCESS_TOKEN}"`

The DEFAULT_PUBLIC_ACCESS_TOKEN can be obtained by creating an account on mapbox.com

I hope this helps at least one person! :)
