### ISSUE TITLE
The use of Leaflet.awesome-markers

### ISSUE THREAD

**Issue by rougeth** [python-visualization/folium#947]
I would like to discuss the use of the Leaflet.awesome-markers library on `folium.map.Icon`. It isn't maintain since 2014 (the last commit is from 2017, but only change the `README.md`) and has several opened issues and pull requests. The project has a lot of forks, but none of them is updated too.

I understand that open source is hard and you probably don't have enough hands to handle the important issues and pull requests that Folium gets itself, so taking care of fancy icons is definitely not a priority.

But, having an old and unmaintained feature can make users frustrated (my case). The library itself is pretty small and simple and I believe would be great to incorporate it to Folium or at least to the organization. The greatest benefit is that would be much easier to have updates.

I would like to help. If you're interest in my suggestions, I can do the work of moving the library to inside and help to maintain it.

**Comment by ocefpaf** [comment]
>  If you're interest in my suggestions, I can do the work of moving the library to inside and help to maintain it.

Please do! I haven't check the status of `Leaflet.awesome-markers` in ages like you said. @Conengmo is probably more up-to-date with the current status of those issues.

**Comment by Conengmo** [comment]
Indeed this issue came up recently in #923. I did a quick search then but also didn't see a clear replacement fork that was working on adopting Font Awesome 5.

In my opinion the best option would be if one of the forks would actively maintain and update the library. If there is no such fork, we could fork it into the python-visualization group as you suggest and do any updates we want. Alternatively, we could directly adopt it into folium. This could make sense, since we don't have to expose the full feature range, only what we want to make available through the folium Python interface.

I'm not sure yet what the best way to go is. But I appreciate your help @rougeth! Maybe you can discuss a bit what the different options entail and tell a bit what updates you want to do to the library.

**Comment by rougeth** [comment]
@ocefpaf @Conengmo if we have `Leaflet.awesome-markers` in a different repository, like today, people could use it even it they aren't interested in Folium. Besides that, I cannot see other positive/negative points. The only point is to have the library under the Folium's umbrella so that updates would be easy to do. I would go with the first option, in a separate repository.

@Conengmo I didn't see the #923 before opening this issue, my bad.

**Comment by rougeth** [comment]
I will check the host options and once we have it ready and updated here, we can start working on new things like the CI.
