### ISSUE TITLE
Adding textures to polygons

### ISSUE THREAD

**Issue by ColinTalbert** [python-visualization/folium#960]
First off many thanks for creating this awesome package.

I'm interested in adding textures to polygons and think it should be doable using the textures.js package.  I've started playing around with using texture.js to implement this.  Here's the notebook of what I've got so far:
http://nbviewer.jupyter.org/gist/talbertc-usgs/b758306f86bec054ca747887a476ab83

I think I'm close, but I'm new to javascript, D3, and the like so I may be way off.
The two issues I think I have:
1) The svg that I'm calling the texture on is it the same one the map is rendering on?
2) the fill is coming out as a string "t8.url();" instead of executed code t8.url();

I'd love to finish this add contribute a PR to the package (or pluggin) if appropriate.

-- Colin
folium.__version__ = 0.6

**Comment by Conengmo** [comment]
Interesting stuff @talbertc-usgs. Nice idea to add textures/patterns.

In you gist I see you got it working on the circle example. But not on the geojson yet. You're right about issue 2, the style declaration is coming out as a string "t8.url();" instead of code. You can fix this manually in the html for now, later we could implement this in the template directly. But still it didn't work for me.

I'm hesitant about working with d3 directly. It has a steep learning curve so maintaining it in this mainly Python project will be hard. 

Two suggestions:

- Is there not already a way to add patterns using native Leaflet? https://leafletjs.com/reference-1.3.4.html#path-option
- Is there not a Leaflet plugin that does this? https://leafletjs.com/plugins.html
  - https://github.com/teastman/Leaflet.pattern
  - https://github.com/cloudybay/leaflet-polygon-fillPattern

I hope you want to check out my suggestions and see if that could work.

**Comment by talbertc-usgs** [comment]
Thanks for pointers.  I'm still getting my bearings on the organization of the project so this is helpful.  I was thinking D3 was more easily integrated because I saw a reference here: https://github.com/python-visualization/folium/blob/master/folium/plugins/time_slider_choropleth.py#L169

You are probably right though that a more native implementation of textures would be easier to implement and maintain. 

I'm not seeing anything in native leaflet, that handles it, but I could be missing something.
On cursory overview I think that first plugin looks promising.  Would it be appropriate for me to try my hand at building a folium plugin for that?  I was thinking I could model it off of one of the existing plugins such as: https://github.com/python-visualization/folium/blob/master/folium/plugins/polyline_text_path.py

But direction or hints for contributing would be welcome.

Thanks

**Comment by Conengmo** [comment]
> I was thinking D3 was more easily integrated

D3 is indeed already included, for example in the plugin you reference. But in general importing a Leaflet plugin is much more high-level than working with d3 directly. 

>  Would it be appropriate for me to try my hand at building a folium plugin for that?

Definitely. This is currently the way most plugins of folium work. Import the javascript Leaflet plugin, call it with a simple template, expose some options through the Python class, done! We have a lot of dependencies with this way of working, but it beats writing everything from scratch ourselves.

By the way I noticed the first plugin (Leaflet.pattern) appeared on a wishlist a while back already. I seems a good call to use this one instead of the second one.

**Comment by talbertc-usgs** [comment]
PR submitted!

**Comment by Conengmo** [comment]
This was merged in https://github.com/python-visualization/folium/pull/966
