### ISSUE TITLE
ColorLine opacity shows dark spots at joints b/c segments overlap

### ISSUE THREAD

**Issue by gidven** [python-visualization/folium#967]
Love your work on this!!

Just wanted to notify you all that I noticed overlapping segments in the ColorLine function cause dark spots to appear at the ends of segments when using opacity:

```python
import folium

test_map = folium.Map(location=[51.5, -0.115],
                      zoom_start=13,
                      tiles='cartodbpositron')

folium.ColorLine([(51.49, -0.10),
                  (51.50, -0.105),
                  (51.51, -0.103),
                  (51.52, -0.11)],
                 colors = [0,1,2],
                 colormap = ['green', 'red'],
                 weight = 10,
                 opacity = 0.25).add_to(test_map)

test_map

```
#### Problem description

From what I understand, each line is generated separately. When the lines are overlaid, the opacity setting causes 'doubling' at the joints. When opacity is set to 1, it shows each next line is laid on top of the previous one.

#### Expected Output

Ideally, these joints should show with the intended opacity. This is tricky thing to solve, as reducing line length and re-designing the joints is not really feasible. One way it might be solvable is by overlaying a circle at the joint with matching width/radius as the line, and have it 'inverse' opacity back to the intended value. I am by no means an expert and don't even know if this is technically possible.

#### Output of ``folium.__version__``

'0.6.0'

**Comment by Conengmo** [comment]
You're right about this. Unfortunately this is not a thing we can fix in folium. Not even in Leaflet, since this is fundamental to how opacity works. See also this Leaflet issue:  

https://github.com/Leaflet/Leaflet/issues/3610

I did find a possible workaround here: https://stackoverflow.com/questions/18334135/leaflet-overlapping-shapes-opacity

If you set the opacity in folium to 1 you can set the opacity on a parent div. You can check which elements are there in your browser dev tools. I made an example how you can add the css:

```
m = folium.Map()
element = folium.MacroElement().add_to(m)
element._template = jinja2.Template("""
    {% macro header(this, kwargs) %}   
    <style>div.leaflet-overlay-pane > svg.leaflet-zoom-animated {
        opacity: 0.5;
    }
    </style>
    {% endmacro %}
""")
```

I'm adding an element to the map that is added to the header. I'm applying the opacity on all svg's with the `leaflet-zoom-animated` class that have a parent div with class `leaflet-overlay-pane`.

**Comment by Conengmo** [comment]
I'm closing this issue, since I think the hack I proposed is not something we should incorporate in folium. Other ideas or comments are welcome! We can reopen the issue if needed.
