### ISSUE TITLE
Unexpected widening of range in choropleth

### ISSUE THREAD

**Issue by LeonardoFurtado** [python-visualization/folium#971]
#### Code

```python
import pandas as pd
import os
import folium

state_geo = os.path.join('', 'countries.geo.json')

state_unemployment = os.path.join('', 'new.csv')
state_data = pd.read_csv(state_unemployment)

m = folium.Map(location=[48, -102], zoom_start=3)

m.choropleth(
    geo_data=state_geo,
    name='choropleth',
    data=state_data,
    columns=['State', 'Unemployment'],
    key_on='feature.id',
    fill_color='YlGn',
    fill_opacity=0.7,
    line_opacity=0.2,
    legend_name='Unemployment Rate (%)'
)


folium.LayerControl().add_to(m)

m.save('output.html')

```
#### Problem description

Why does Folium show me that I have negative value records? the lowest value record is 0, and the highest value is 500, however the map caption looks like this:
![sem titulo](https://user-images.githubusercontent.com/22118060/46113421-acb39080-c1c4-11e8-8429-a99dc25420a5.png)

**Comment by Conengmo** [comment]
There are some things going on in the `choropleth` method to get to this color scale. I'm not that familiar with the details, but it seems the minimum and maximum value of the color scale are not the same as the min and max of the data.

See for example [this line](https://github.com/python-visualization/folium/blob/master/folium/folium.py#L554):

```
data_min, data_max = (1.01 * data_min - 0.01 * data_max,
                      1.01 * data_max - 0.01 * data_min)
```

As far as I can see this has been there since forever :) so I can't check why they did it like this. Maybe it's because elsewhere a strict inequality is used, so some slack is needed on the range, I'm not sure.

A work-around for now is to provide explicit color threshold values:
```
m.choropleth(
    ...,
    threshold_scale=[0, 2, 4, 8, 16, 32],
)
```

I don't think the slack is needed, so the behavior can probably be changed. But we need to be certain nothing breaks.

**Comment by Conengmo** [comment]
How shall we go forward on this? I suggest removing the slack around the min and max values. @LeonardoFurtado do you want to open a PR with this?
