### ISSUE TITLE
Toggle or Show parameter for choropleth layers not working as expected

### ISSUE THREAD

**Issue by skoeb** [python-visualization/folium#981]
`#`### Please add a code sample or a nbviewer link, copy-pastable if possible

```python
m.choropleth(name = 'Registered Electric Vehicles',geo_data = zips, data = zips, key_on='feature.properties.ZIP',
                     columns=['ZIP','EV'], fill_color='BuGn', line_weight = 0.3, line_opacity = 0.5,
                     fill_opacity = 0.5, legend_name = 'Registered Electric Vehicles', 
                     smooth_factor = 1, toggle = True)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-54-828389e26172> in <module>()
     11                      columns=['ZIP','PHEV'], fill_color='RdPu', line_weight = 0.3, line_opacity = 0.5,
     12                      fill_opacity = 0.5, legend_name = 'Registered Plug-in Hybrids',
---> 13                      smooth_factor = 1, toggle = True)
     14 m.choropleth(name = 'Registered Electric Vehicles',geo_data = zips, data = zips, key_on='feature.properties.ZIP',
     15                      columns=['ZIP','EV'], fill_color='BuGn', line_weight = 0.3, line_opacity = 0.5,

TypeError: choropleth() got an unexpected keyword argument 'toggle'
```
#### Problem description
I have a map with multiple choropleth layers that I want available to select in LayerControl, but I only want one to display on load. 

Based on #772 and #606 it seems like anything inheriting the `Layer` class should have the parameter `toggle` to enable or disable the layer on load. This doesn't work for choropleths, which I had thought inherited the Layer class. I've also tried adding the choropleth to a `FeatureGroup` with `show = False`, but this doesn't work because choropleth is a method of a `Map` object.  

What am I doing wrong? or is there not currently a way to only display one choropleth layer on load?

#### Output of ``folium.__version__``
0.6.0

**Comment by Conengmo** [comment]
Hi @skoeb, thanks for your issue report. You're right that there is no way to use a `show` parameter with `choropleth`, since it is a method of `Map` indeed. A hack would be to look in the children of your `Map` object and change it there, but that's not a good way to solve this.

I've been meaning to move `Map.choropleth()` to it's own class for a while. That would make it consistent with the other folium classes. The proposed `Choropleth` class would be sort of empty itself, but would contain two children: `GeoJson` or `TopoJson` object and `StepColorMap` object. Or maybe a `FeatureGroup` with both of them in them? At least that's what we need to try out. The `Map.choropleth()` method could than call that new class, with a deprecation warning.

Maybe you want to help with this and open a PR?

**Comment by skoeb** [comment]
Hi @Conengmo, I'm not sure if I have the time to put together a PR right now, but for others who stumble on this I managed to make this work by looping through a geodataframe with `folium.GeoJson` and setting the color from a geodataframe column with the `style_function` argument.

**Comment by Conengmo** [comment]
choropleths are now made by using the `Choropleth` class, which has a `show` argument. See also the example notebook on geojson and choropleths.

**Comment by skoeb** [comment]
Thanks @conengmo! This is a great improvement and lets me delete a lot of spaghetti.

**Comment by ocefpaf** [comment]
> Thanks @Conengmo! This is a great improvement and lets me delete a lot of spaghetti.

BTW. I'm working on a new release later today that will incorporate that change. Thanks @skoeb for raising the issue and @Conengmo for fixing it!
